<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE diseases [
<!ELEMENT diseases (disease)*>
<!ELEMENT disease (name?, related_diseases?, related_symptoms?, medDeps?, synonym?, description?)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synonym (#PCDATA)>
<!ELEMENT related_diseases (related_disease)*>
<!ELEMENT related_disease (#PCDATA)>
<!ELEMENT related_symptoms (related_symptom)*>
<!ELEMENT related_symptom (#PCDATA)>
<!ELEMENT medDeps (medDep)*>
<!ELEMENT medDep (#PCDATA)>
<!ELEMENT description (definition?, cause?, symptom?, diagnosis?, progress?, caution?)*>
<!ELEMENT definition (#PCDATA)>
<!ELEMENT cause (#PCDATA)>
<!ELEMENT symptom (#PCDATA)>
<!ELEMENT diagnosis (#PCDATA)>
<!ELEMENT progress (#PCDATA)>
<!ELEMENT caution (#PCDATA)>
]>
<!--Seongtae Kim 2020-06-06 https://github.com/Seongtae-Kim -->
<diseases>
  <disease>
    <name>대상포진(Herpes zoster)</name>
    <related_diseases>
      <related_disease>헤르페스 바이러스 감염</related_disease>
      <related_disease>수두</related_disease>
      <related_disease>대상포진후 신경통</related_disease>
      <related_disease>구순포진</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>딱지</related_symptom>
      <related_symptom>환부 통증</related_symptom>
      <related_symptom>두통</related_symptom>
      <related_symptom>발진</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>수두-대상포진 바이러스(varicella-zoster virus, VZV)가 소아기에 수두를 일으킨 뒤 신경 주위에서 무증상으로 남아 있다가 수두-대상포진 바이러스에 대한 면역력이 떨어지면 신경을 타고 나와 피부에 발진이 생기면서 심한 통증을 유발하는 질병입니다.</definition>
      <cause>주로(세포 매개성) 면역력이 떨어진 상태(고령, 면역저하제 사용, 이식, 에이즈 등)에서 바이러스가 증식하여 신경을 따라 피부로 다시 나오는 것으로 알려져 있습니다. 암, 에이즈, 항암 치료, 방사선 치료, 이식 후 거부 반응을 막기 위해 면역억제제를 복용하는 경우, 장기간 스테로이드 복용하는 경우 면역력이 감소할 수 있고  질병, 사고, 스트레스 등으로 우리 몸의 면역력이 약해졌을 때 대상포진이 발생할 수도 있습니다.</cause>
      <symptom>대상포진은 주로 몸통이나 엉덩이 부위에 잘 생기지만 신경이 있는 부위이면 어디든지(얼굴, 팔, 다리 등) 발생할 수 있습니다.
주로 발생하는 증상은 통증입니다. 몸의 한쪽 부분에 국한되는 경우가 대부분이며 아프거나 따끔거리는 증상이 발생합니다. 이러한 증상이 1~3일간 지속된 이후에 붉은 발진이 일어나게 되고 열이나 두통이 발생하게 됩니다. 수포는 2~3주간 지속되며 이것이 사라지면 농포나 가피가 형성되고 점차 사라지게 됩니다.

통증은 병변이 사라진 후에도 지속될 수 있습니다. 이를 포진 후 신경통이라고 합니다. 매우 드물기는 하지만 수포 없이 통증이 발생하거나 통증 없이 수포가 발생하는 경우도 있습니다.  포진 후 신경통은 통증이 매우 심하여 일반적인 진통제에 잘 반응하지 않는 아주 심한 경우 신경 차단술 등을 시행하기도 합니다.</symptom>
      <diagnosis>대상포진의 수포가 신경을 따라 무리를 지어 특징적(발진, 수포, 농포, 가피의 여러 단계가 산재한 양상)으로 나타나기 때문에 이러한 피부 병병의 모양만으로도 진단에 이르게 되는 경우가 많습니다. 그러나 전형적인 피부 변화를 나타나지 않는 경우도 있기 때문에 피부 병변을 긁어 현미경적 검사, 바이러스 배양, 또는 분자 유전자 검사를 할 수 있습니다.</diagnosis>
      <progress>대상포진 후 신경통은 병변이 치료된 이후에 계속 아픈 것을 말합니다. 이는 기본적으로 바이러스가 신경을 타고 피부로 나오기 때문에 신경에 염증이 생기면서 통증이 지속적으로 남아 있는 것으로 이해되고 있습니다. 이러한 통증은 수개월 동안 지속되거나 수년 동안 지속될 수 있으며, 노인에게 호발합니다.
  대상포진 초기에 약을 쓰는 경우에 이러한 합병증을 줄일 수도 있습니다. 또 대상포진백신을 투여받는 경우에는 이러한 포진 후 신경통의 빈도가 낮아지는 것으로 알려져 있습니다.

다른 합병증으로는 대상포진 바이러스가 내부 장기에 퍼지게 되는 것입니다. 이 경우에는 수두와 비슷하게 보이며, 주로 면역력이 떨어진 사람에서 이런 증상이 나타납니다.</progress>
      <caution>수포 부위에 박테리아 감염이 되는 경우 치료가 지연됩니다. 만약 통증이 지속되고 붉은 기운이 증가하거나 다시 나타나게 되면 반드시 의사와 상담해야 합니다.</caution>
    </description>
  </disease>
  <disease>
    <name>백반증(Vitiligo)</name>
    <related_diseases>
      <related_disease>광선 각화증</related_disease>
      <related_disease>어린선</related_disease>
      <related_disease>모공성 각화증</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>모발 탈색</related_symptom>
      <related_symptom>하얀 반점</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>멜라닌세포 소실에 의해 다양한 크기와 형태의 백색반들이 피부에 나타나는 후천적 탈색소질환 중 가장 흔한 질환입니다.
인구의 약 0.5~2%에서 나타나는 흔한 질환으로 인종이나 지역에 차이 없이 발생하며, 대개 10~30세 사이에 가장 많이 발생합니다.</definition>
      <cause>정확한 원인은 아직 알려지지 않았으나 높은 가족력으로 미루어보아 유전적 소인이 관여할 것으로 추측되며 면역설, 신경체액설, 멜라닌세포 자가파괴설의 3가지 학설이 복합적으로 기여하는 것으로 설명하고 있습니다.
  면역설의 경우 백반증 환자에서 기관특이성 자가항체의 비율이 높고 멜라닌세포계 항원에 대한 자가항체의 발생이 많다는 점으로 뒷받침되고 있습니다. 신경체액설은 멜라닌세포가 신경능에서 기원하며 백반증이 신경절에 따른 분포를 보이거나 신경손상 혹은 정신적 스트레스 후 발병하는 경우가 있다는 점 등에 의해 뒷받침됩니다. 그 외에도 항산화효소 부족, 칼슘 섭취 이상, 외상, 햇볕에 의한 화상 등이 백반증의 발생 또는 악화와 관련되기도 합니다.</cause>
      <symptom>피부 탈색, 백모증(모발 탈색)이 일어납니다. 탈색반의 경계가 분명하고 탈색소성의 대칭성 반이 어느 부위에서나 생길 수 있습니다. 뼈가 돌출된 손, 발, 팔꿈치, 무릎 등과 얼굴, 아랫배 등에 잘 생깁니다. 때로는 흰 반점의 경계부가 오히려 검게 나타나기도 합니다. 흰 반점이 나타나는 것 외에 다른 자각 증상은 거의 없고 아주 드물게 병변 부위가 가렵거나 따끔따금한 경우도 있습니다. 백반증은 특이적으로 물리적 화학적 외상을 입은 곳에서 발생할 수 있습니다.</symptom>
      <diagnosis>대개 육안적 관찰로써 쉽게 진단할 수 있습니다. 그러나 피부에 흰색 반점이 나타나는 질환은 백반증 외에도 다양하므로 반상 피부경화증, 백색잔비늘증, 어루러기, 염증 후 탈색증 등과의 감별을 요하며 때로는 감별이 어려운 경우도 있습니다.</diagnosis>
      <progress>백반증은 완치가 불가능한 경우도 있으며, 색소가 소실되는 시기와 그 소실이 멈추는 시기가 끊임없이 반복하기도 하며 저절로 돌아오는 경우는 드뭅니다. 꾸준한 치료가 요구되는 질환입니다. </progress>
      <caution>백반증 환자는 일상생활에서 피부에 자극이나 상처를 받지 않도록 조심해야 합니다. 왜냐하면 상처를 입는 후에는 그 부위에 백반증이 생기거나 더 펴져나갈 수 있기 때문입니다. 그 다음 자외선을 피해야합니다. 백반증 환자는 그 부위에 멜라닌 색소가 없어 일광 화상을 잘 받을 수 있기 때문입니다.  </caution>
    </description>
  </disease>
  <disease>
    <name>여드름(Acne)</name>
    <related_diseases>
      <related_disease>지루성 피부염</related_disease>
      <related_disease>모낭염</related_disease>
      <related_disease>다낭성 난소증후군</related_disease>
      <related_disease>피부염</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>낭종</related_symptom>
      <related_symptom>고름</related_symptom>
      <related_symptom>면포</related_symptom>
      <related_symptom>결절</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>여드름은 털을 만드는 모낭에 붙어 있는 피지선에 발생하는 만성 염증성 질환입니다. 보통 사춘기에 발생하지만 어른들에게도 나타날 수 있습니다. 잘 생기는 곳은 얼굴, 목, 등, 가슴 등과 같이 유분이 많은  피부 부위입니다.
  정상 상태에서는 피지는 모낭 벽을 따라 위로 올라가 피부를 통해 밖으로 배출되게 되지만 피지가 피부 밖으로 배출되지 못하고 모낭 주위에 갇히게 되면 염증을 불러일으키는 박테리아가 번식하게 되는데, 이것이 여드름이 되는 것입니다.
 </definition>
      <cause>호르몬의 변화, 세균 감염, 유전성 요인 등이 관련된 것으로 생각되나 정확한 원인은 아직 모르는 상태입니다. 대체로 사춘기에 나타나는 여드름은 안드로겐이라는 남성호르몬의 자극에 의해 피지를 과다하게 내보내기 때문에 발생합니다. 하지만 성인 여드름의 경우는 여성에게서 많이 나타나며 생리 전 주기적으로 악화되는 것을 볼 수 있습니다. 이는 프로게스테론이라는 황체호르몬, 지나치게 기름이 많거나 털구멍을 밀폐시키는 화장품 등이 원인 또는 악화 인자가 될 수 있습니다. 또한 정서적 긴장이나 스트레스, 수면 부족 등으로 부신피질 호르몬이 분비되어 피지선을 자극하여 발생합니다.</cause>
      <symptom>여드름의 증상으로 면포, 구진, 농포 등이 나타나며 심한 경우에는 결절이나 낭종이 생기게 됩니다. 면포란 피지가 축적되어 모낭이 팽창된 것입니다. 면포에는 모낭 입구가 열려 있어 이때 보이는 축적된 피지의 색이 검게보이는 개방 면포, 즉 우리가 흔히 말하는 블랙헤드와 표면이 닫혀 있는 폐쇄 면포인 화이트헤드 두 가지 형태가 있습니다. 면포가 오래되면 주위에 세균이 증식하고 그 주위에 염증 세포가 모이게 되면 붉은 여드름 구진과, 곪는 여드름 농포를 형성하고, 이 정도가 심해져 부어 있는 결절과 낭종 등의 상태로 나타나게 됩니다.</symptom>
      <diagnosis>보통 간단한 검진만으로 여드름을 진단하게 됩니다. 얼굴, 가슴, 등, 팔, 어깨 등 증상이 발생한 부위를 관찰하고 환자의 병이나 건강상태에 대한 질문을 통해 여드름 유발에 관련 있는 요소들은 없는지 찾아내게 됩니다. 다만, 심한 경우 원인 질환을 감별하기 위해 여러 가지 호르몬 검사를 시행하고 있습니다.</diagnosis>
      <caution>보통 여드름은 사춘기부터 시작되어 20대 중반에는 사라지지만 최근에는 계속 지속되거나 새로 발생하는 성인 여드름이 증가하고 있습니다. 성인 여드름의 경우 사춘기 시기보다 유병기간이 길고 치료 반응도 느리게 나타난다고 합니다. 물론 가벼운 여드름은 자연적으로 소멸할 수도 있고, 치료 없이도 좋아졌다 나빠졌다 하기도 합니다. 하지만 초기에 치료하는 것이 중요하고, 그렇지 않을 경우 피부 붉어짐, 색소 변화, 흉터 발생의 위험성이 높으므로 적절한 치료가 필요합니다.</caution>
    </description>
  </disease>
  <disease>
    <name>모낭염(Folliculitis)</name>
    <related_diseases>
      <related_disease>여드름</related_disease>
      <related_disease>수면 장애</related_disease>
      <related_disease>모공성 각화증</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>고름</related_symptom>
      <related_symptom>면포</related_symptom>
      <related_symptom>체모감소</related_symptom>
      <related_symptom>오한</related_symptom>
      <related_symptom>열</related_symptom>
      <related_symptom>여드름</related_symptom>
      <related_symptom>환부 통증</related_symptom>
      <related_symptom>발적</related_symptom>
    </related_symptoms>
    <medDeps>
      <medDep>여드름</medDep>
      <medDep>수면 장애</medDep>
      <medDep>모공성 각화증</medDep>
    </medDeps>
    <synonym></synonym>
    <description>
      <definition>모낭염이란 세균(특히 포도상구균)감염, 화학적, 물리적 자극에 의하여 모낭(털구멍)에 염증이 생기는 것입니다.</definition>
      <cause>모낭염은 스트레스나, 과로, 수면 부족 등에 의해 면역력이 약해진 피부 속으로 균이 침투해 생기는 것입니다. 예를 들어 콧속의 털을 뽑거나 겨드랑이 털을 면도하거나 타르나 석유 혹은 파라핀이 모공 속으로 들어갔을 경우에 발생합니다. 원인균은 대체로 독성이 약한 표피 포도상구균일 때가 많으나 황색포도상구균에 의한 염증인 경우도 있습니다</cause>
      <symptom>모낭염은 부위와 원인에 따라 차이를 보입니다. 보통 전신 증상이 없고 털이 있는 곳, 대체로 두피나 팔다리에 주로 발생하지만 어느 부위에서나 발생할 수 있습니다. 균이 침입한 부위는 가렵고 통증이 있으며, 좁쌀같이 노랗게 곪은 형태로 나타납니다.

모낭을 중심으로 붉은 반점이 생기면서 작은 구진 또는 농포가 생기는 경우도 있는데 이 때 발열, 오한 등 전신 증상이 심하여 국소 림프절이 붓기도 하고 털을 중심으로 단단하고 통증이 심한 홍색 결절이 나타나기도 합니다. 가피가 형성되지만 적당한 치료를 했을 때는 흉을 남기지 않고 치료됩니다. 균이 피부의 표피에만 머물지 않고 더 깊숙히 침입한 경우에는 흉터가 생기기도 하며 탈모가 되기도 합니다.</symptom>
      <diagnosis>전문의에 의한 진단 및 검진 농포 배설물 배양법이 있습니다.</diagnosis>
      <progress>치료를 하면 2주내에 완전히 회복되나 재발하는 것이 보통입니다. 극소수이긴하나 감염이 혈액내로 침입하여 몸 전체에 퍼질 경우 패혈증을 일으킬 수도 있습니다.  </progress>
      <caution>모낭염을 예방하는 생활습관 관리로는

1. 세균이 성장하기에 적합한 후덥지근한 곳은 피하는 것이 좋습니다.

2. 염증의 원인균이 다른 부위로 전염되지 않도록 농포를 긁지 않아야 합니다.

3. 면도를 할 때 각질층까지 일부 제거되므로 세균 감염으로 모낭염 등이 생길 수 있으므로 면도기를 청결하게 관리하여 감염을 방지하는 것이 중요합니다.

4. 면도기는 반드시 자신의 것만을 사용하여 모낭염이 전염되는 것을 막아야 합니다.

5. 영양분과 유분이 함유된 로션은 면도로 자극받은 피부에 바로 바르면 곪거나 덧나는 원인이 될 수 있으므로 주의하셔야 합니다.

6. 두피를 청결하게 유지해 주어야 합니다. 하루 활동 후 땀, 피지, 오염 물질 등으로 지저분해진 두피와 모발을 깨끗이 관리하기 위해 저녁때 감는 것이 좋습니다.

7. 머리를 말릴 때는 반드시 뜨겁지 않은 드라이어의 바람을 사용해야 합니다. 뜨거운 바람으로 단시간에 머리를 말리는 방법은 오히려 두피의 수분을 증발시켜서 두피가 건조해지고, 염증에 영향을 줄 수 있습니다.</caution>
    </description>
  </disease>
  <disease>
    <name>피부암(Skin cancer)</name>
    <related_diseases>
      <related_disease>백반증</related_disease>
      <related_disease>화상</related_disease>
      <related_disease>악성 흑색종</related_disease>
      <related_disease>광선 각화증</related_disease>
      <related_disease>카포시 육종</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>딱지</related_symptom>
      <related_symptom>색소 침착</related_symptom>
      <related_symptom>점 안에 다른 색 피부</related_symptom>
      <related_symptom>환부 통증</related_symptom>
      <related_symptom>피부궤양</related_symptom>
      <related_symptom>결절</related_symptom>
      <related_symptom>갈색 피부 반점</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>피부에 발생되는 악성 종양을 의미합니다. 피부에 발생하는 양성 종양과는 구별되는 것입니다. 원발성 피부 악성 종양은 기저세포암, 편평세포암, 악성 흑색종이 대부분을 차지합니다.
 </definition>
      <cause>햇빛에 의한 손상이 피부암의 주요 원인으로 알려져 있습니다. 햇빛의 자외선은 DNA에 손상을 입혀서 세포 성장과 분화에 영향을 주게 됩니다. 따라서 태양광에 노출이 많이 될수록 위험성이 커지며 태양에 많이 노출되는 부위에 발생 위험이 높습니다. 또 위도가 낮을수록 피부암 발생이 빈번합니다. 

화학물질로서는 비소가 피부암 발생과 관련된 것으로 알려져 있습니다.
바이러스 감염도 피부암 발생의 원인이 될 수 있으며, 면역억제된 환자들, 즉 장기이식 환자나 에이즈 환자에서 피부암이 더 흔히 나타납니다.</cause>
      <symptom>1. 기저세포암
여러 임상 형태를 나타낼 수 있으며, 얼굴 부위에 주로 호발합니다. 기저세포암은 서서히 자라고 몸의 다른 부위에 전이를 일으키는 경우가 드뭅니다. 그러나 주위 피부 및 피하와 근육, 심지어는 뼈까지도 국소적으로 침입할 수 있습니다.
  기저세포암의 형태를 통해 증상을 본다면
(1) 결절궤양기저세포암: 가장 흔한 형태로 밀랍모양으로 반투명한 표면에 모세혈관확장이 있는 작은 결절로 시작하여 서서히 자라나며 중앙부에 궤양이 생기게 됩니다.
(2) 색소기저세포암: 멜라닌을 함유하고 있어 갈색 또는 검은색으로 보이며 악성흑색종과의 감별이 요구됩니다.
(3) 경화기저세포암: 표면이 매끄럽고 편평하거나 약간 낮거나 높으며 상아색조를 띠고 단단한 판을 형성합니다. 치료 후 재발이 흔한 형태입니다.
(4) 표재기저세포암: 한 개 내지 수개의 반이 홍반과 인설이 있고, 약간만 침윤하면서 주로 주변부로 퍼집니다. 몸통과 팔다리에 흔합니다.
  2. 편평상피암
편평세포암은 얼굴, 아랫입술, 귀 등에 호발합니다. 광선각화증, 화상에 의한 흉터나 만성 궤양이 있었던 부위에서 발생하는 경우가 많으며, 대개 작고 단단한 결절로 시작하여 결절판상, 사마귀 모양, 궤양 등 다양한 형태로 진행합니다. 기저세포암에 비해 다른 부위에 전이될 가능성이 높습니다.
  3. 악성 흑색종
검은 반점이나 결절 형태로 흔히 나타나지만 때로는 색소침착이 없는 경우도 있습니다. 비대칭적이고 경계가 불규칙하며 다양한 색조와 0.6cm 이상의 크기를 가질 때, 이미 있던 점의 모양, 크기, 색조가 변하거나 가려움증, 따가움, 통증이 생기거나, 출혈, 궤양, 딱지 형성 같은 변화를 보일 때 의심해 볼 수 있습니다. 흑색종은 전이가 흔히 발생하고 진행될 경우 예후가 좋지 않습니다.</symptom>
      <diagnosis>정확한 진단을 위해서는 국소마취를 하고 피부 병변의 일부를 떼어내 조사하는 피부 생검을 해야 합니다. 흉부 X-촬영과 복부 초음파검사를 비롯해, 방사성 동위원소를 사용한 검사, CT 촬영,  MRI 등의 정밀검사를 통해 종양의 침윤(주위로 퍼지는 것) 깊이나 전이 등, 병의 확산 정도를 알아볼 수 있습니다.</diagnosis>
      <progress>조기 발견하면 완치가 가능하고 예후도 좋습니다. 그러나 악성 흑색종의 경우는 예후가 좋지 않으므로 초기에 정확히 진단하고 종양세포의 침습 정도를 파악하여 치료해야 합니다.</progress>
    </description>
  </disease>
  <disease>
    <name>곰팡이 감염(Fungal infection)</name>
    <related_diseases>
      <related_disease>무좀</related_disease>
      <related_disease>조갑백선</related_disease>
      <related_disease>진균성 각막 궤양</related_disease>
      <related_disease>어린선</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>발가락 사이 갈라짐</related_symptom>
      <related_symptom>피부 각질</related_symptom>
      <related_symptom>피부소양감</related_symptom>
      <related_symptom>손,발톱이 갈라짐</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>곰팡이 감염(피부 표재성 곰팡이증)은 진균이 피부의 가장 바깥층인 각질층, 손발톱, 머리카락을 감염하여 발생하는 질환을 의미합니다. 병변 부위에 따라 머리 백선, 체부 백선, 서혜부 백선, 족부 백선, 손발톱 백선, 얼굴 백선, 손 백선 등으로 분류됩니다.
이 질환을 유발하는 곰팡이는 균사를 분지하면서 자라는 가는 선 모양의 곰팡이와 단세포의 효모균류로 구분됩니다. 곰팡이류는 포자를 만드는데, 이 포자는 질병을 유발하기 이전 수년 동안 비활성화 상태로 존재하기도 합니다.
  ① 균사체
균사체는 '균사'라고 불리는 긴 튜브 모양의 가지를 형성합니다. 균사체는 '격막'이라 불리는 막을 경계로 분리되어 번식합니다.
  ② 효모균류
효모균류는 원형 또는 타원형의 단세포 생물로 군집을 이루어 살아갑니다. 효모균류는 세포 분열과 이분법으로 번식합니다.
    곰팡이 감염은 진균 도말 검사로 진단합니다.
검사 방법은
① 곰팡이 감염이 의심되는 환자의 병변 부위에서 소독한 수술칼 등을 이용하여 검체(피부의 각질이나 물집에서 나온 진물 등)를 얻습니다.
② 칼로 긁어낸 검체를 슬라이드에 올리고 KOH(수산화칼륨) 20% 용액 등을 커버 슬라이드의 양측에 소량 침투시킵니다.
③ 검체를 올려놓은 슬라이드를 알코올램프 위에서 5분 정도 달군 후 슬라이드를 거즈로 살짝 눌러서 검체를 퍼트립니다.
④ 슬라이드를 현미경으로 확인합니다.
  발에 생기는 곰팡이 감염이 ‘무좀’입니다. 무좀을 예방하기 위해서는 하루 1회 이상 발을 씻고, 땀을 많이 흘리거나 운동을 하는 경우 더 자주 씻어야 합니다. 발을 씻은 후 발가락 사이를 잘 말리고 건조하게 유지해야 합니다. 신발은 통풍이 좋고 굽이 낮으며 앞부분이 넓은 것을 사용해야 합니다. 여성의 경우 스타킹의 착용을 줄일 필요가 있습니다.
   </definition>
    </description>
  </disease>
  <disease>
    <name>사마귀(Wart)</name>
    <related_diseases>
      <related_disease>첨형 콘딜로마</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>검은 점</related_symptom>
      <related_symptom>사마귀 위 털이 많음</related_symptom>
      <related_symptom>결절</related_symptom>
    </related_symptoms>
    <medDeps>
      <medDep>첨형 콘딜로마</medDep>
    </medDeps>
    <synonym></synonym>
    <description>
      <definition>사마귀란 사람 유두종 바이러스 감염으로 피부 및 점막의 증식이 발생하는 질환입니다.</definition>
      <cause>사마귀는 사람 유두종 바이러스의 감염에 의해 생깁니다.
 </cause>
      <symptom>사마귀로 인한 병변은 대체로 표면이 거칠게 융기되는 구진이나 판의 형태로 나타납니다.

1. 보통 사마귀
손가락, 손톱 주위, 손등 등에 잘 생기고, 가장 흔한 형태입니다. 주로 5세에서 20세 사이에 생기고, 성인이 되면 발생 빈도가 낮아집니다.
  2. 손발바닥 사마귀
발바닥 사마귀는 체중에 의해 눌려서 피부 표면으로 두드러지게 올라오지 못하고 티눈처럼 피부 속으로 파고들어서 판을 형성하거나, 결절 형태로 되어 걸을 때 통증을 유발하기도 합니다.

3. 편평 사마귀
표면이 편평하고 정상 피부보다 조금 융기되어 있으며 크기는 2~4 mm 정도 됩니다. 각각의 병변은 둥글지만 서로 융합되어 불규칙하게 합쳐지기도 합니다.

4. 음부 사마귀, 뾰족 콘딜로마
가장 흔한 성병으로 요도구, 항문주위부에 호발하며 초기에는 표면이 윤기가 나는 작은 구진으로 시작하지만 시간이 경과함에 따라 구진이 모여 산딸기나 닭 볏 모양이 되기도 합니다. 전염력이 매우 강하여 한 번의 성접촉으로 약 50%가 감염될 수 있고 대개 성교 2~3개월 후에 피부 병변이 나타납니다.</symptom>
      <diagnosis>위에서 설명된 증상들을 바탕으로 임상적 진단이 가능한 경우가 많으며 조직검사를 통해서 더욱 확실히 진단할 수 있습니다. 사마귀를 깎을 때 관찰되는 검은 점상의 병변은 사마귀의 전형적 특징입니다.</diagnosis>
    </description>
  </disease>
  <disease>
    <name>건선(Psoriasis)</name>
    <related_diseases>
      <related_disease>탈락 피부염</related_disease>
      <related_disease>피부염</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>고름</related_symptom>
      <related_symptom>인설</related_symptom>
      <related_symptom>발진</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>건선은 피부에 경계가 뚜렷하며 다양한 크기의 은백색의 비늘로 덮여 있는 홍반성 구진 및 판이 형성되는 질환을 의미합니다. 악화와 호전이 반복되는 만성 염증성 피부 질환입니다. 조직학적인 특징은 상피의 과다 증식입니다. 다양한 임상 양상을 보입니다. 
 </definition>
      <cause>건선의 원인은 아직 명확하게 알려지지 않았습니다. 다만 원인으로 추측되는 요소로는 유전적 요인, 환경적 악화 혹은 유발 요인, 면역학적 요인 등이 있습니다. 현재는 유전적 요인을 기반으로 하여 개인의 생활, 환경적 요인이 유발 인자로 작용하고, 면역학적 요인에 의해 각질 형성 세포의 증식 및 염증 반응이 일어나는 것으로 알려져 있습니다. 건선의 악화 또는 유발 요인으로는 피부 외상, 감염, 겨울 같은 차고 건조한 기후, 건조한 피부, 스트레스, 약물 등이 있습니다.</cause>
      <symptom>건선은 주로 대칭성으로 발생하는데, 사지의 폄 쪽(특히 정강이), 팔꿈치, 무릎, 엉치뼈, 두피 등 자극을 많이 받는 부위에 발생합니다. 초기에는 피부에 붉은색의 작은 좁쌀알 같은 발진(구진)이 생기고, 이것이 점점 호두나 계란 크기로 커집니다. 이후 그 주위에서 좁쌀 같은 발진이 새로 생기는데, 이것도 커지면서 서로 합쳐져서 결국 큰 계란이나 손바닥만 한 크기의 발진이 됩니다. 그 위에는 하얀 비늘과 같은 인설이 겹겹이 쌓입니다.
  건선은 대체로 인설로 덮인 판의 형태를 띠며 인설을 제거하면 점상 출혈이 나타납니다. 이는 건선의 특이적인 증상입니다. 드물게 나타나는 농포성 건선의 경우 농포가 주로 나타납니다.
건선 환자의 30~50%에서 손발톱 병변이 확인됩니다. 조갑 함몰, 조갑 박리, 조갑 비후, 조갑하과각화증, 조갑하황갈색반 등 여러 가지 병변이 나타날 수 있습니다.</symptom>
      <diagnosis>의사는 피부와 손톱의 특징적인 변화를 관찰하고, 신체 검진 결과를 기초로 하여 건선을 진단합니다. 전형적인 피부 병변이 나타나지 않는다면 확진을 위해 피부 병리 조직 검사를 시행할 수도 있습니다.</diagnosis>
      <progress>건선의 재발을 완전히 방지하는 치료 방법은 없습니다. 그러나 고혈압이나 당뇨병처럼 지속적인 관리를 통하여 건선 병변을 사라지게 하고 이를 유지할 수 있습니다. 환자에 따라 차이가 있지만, 일단 건선의 병변이 없어지면 수주 내지 수년간 좋은 상태를 유지할 수 있습니다.</progress>
      <caution>건선 환자는 피부에 마찰 또는 긁어서 상처를 입는 경우 상처 부위에 새로운 병변이 발생할 수 있으므로 피부 손상을 입히지 않도록 주의해야 합니다. 이를 위해 목욕 시에도 과도하게 때를 밀지 않도록 해야 합니다. 또 목감기나 편도선염 등 연쇄상구균 감염을 피해야 하며, 정신적 스트레스도 건선을 악화시킬 수 있습니다. 또 건선을 악화시키는 약물의 사용을 피해야 합니다. 건선 환자는 계절, 즉 기후에 민감합니다. 특히 겨울철에 악화가 잘되므로 특히 신경을 써서 치료해야 합니다.</caution>
    </description>
  </disease>
  <disease>
    <name>매복 사랑니(Impacted teeth)</name>
    <related_diseases>
      <related_disease>치은염</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>입 주변 부종</related_symptom>
      <related_symptom>치아 통증</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>매복 사랑니는 뼛 속에 매복되어 잇몸 밖으로 나오지 못한 치아를 말합니다. 아래턱의 사랑니 매복이 가장 흔히 관찰됩니다.
 </definition>
      <cause>사랑니가 공간이 부족하여 맹출하지 못하거나 옆으로 기울어져서 인접치아에 걸려서 맹출하지 못하여 발생합니다. 아래턱의 경우 턱뼈의 크기가 정상에 비하여 작은 경우 매복 사랑니가 흔하게 관찰됩니다.</cause>
      <symptom>사랑니가 뼈에 완전히 매복되어 있는 경우에는 증상이 거의 없습니다. 하지만 잇몸에 염증이 생기면 붓고 통증이 나타나고 고름이 나올 수 있습니다.</symptom>
      <diagnosis>매복 사랑니는 말 그대로 매복되어 있으면 눈으로는 확인되기 어려우며 치아 전체가 나오는 파노라마라는 엑스레이를 촬영하여 잇몸뼈 속에 묻혀 있는 매복치아의 위치를 파악할 수 있습니다. 아래턱뼈에 신경과 근접해 있는 경우는 치과 CT촬영으로 정확한 위치를 파악해야 합니다.</diagnosis>
      <progress>치아가 뼛 속 깊이 있는 경우 치료 과정 중에 중요한 신경이 다칠 수 있기 때문에 구강악안면외과 전문의에게 시술을 받는 것이 좋습니다. 발치 후에는 심하게 붓거나 멍이 들 수 있으며 통증이 있습니다. 수술 도중 신경이 손상을 받으면 부작용으로 입술과 잇몸의 감각 이상이 생길 수 있습니다.</progress>
      <caution>발치 후 피가 멈추게 하기 위해서 거즈를 잘 무는 게 가장 중요하며, 수술 부위의 염증과 통증을 완화하기 위해 항생제 및 진통제를 잘 챙겨 복용해야 합니다. 간혹 부종이 생길 수 있으므로 냉찜질을 48시간 정도 해 주는 게 좋습니다. 술이나 담배 그리고 뜨거운 목욕은 피하는 것이 좋습니다.</caution>
    </description>
  </disease>
  <disease>
    <name>근단 주위 농양(Periapical abscess with sinus)</name>
    <related_diseases>
      <related_disease>치근낭</related_disease>
      <related_disease>치아 우식증[충치]</related_disease>
      <related_disease>치은염</related_disease>
      <related_disease>치주 농양</related_disease>
      <related_disease>급성 치수염</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>열</related_symptom>
      <related_symptom>두통</related_symptom>
      <related_symptom>이가 시림</related_symptom>
      <related_symptom>치근단 부위 부종</related_symptom>
      <related_symptom>잇몸염증</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>치아 뿌리 주변에 염증이 발생하여 치아가 솟은 듯한 느낌으로 갑자기 음식을 씹을 수가 없고 통증이 심하게 올 수 있습니다.
 </definition>
      <cause>근단 주위 농양은 충치가 심해져서 염증이 치아 내 신경까지 파급되어 발생합니다. 신경 치료를 한 이후에 발생하는 경우 치아 뿌리의 파절이 원인일 수 있습니다.</cause>
      <symptom>급성 근단 주위 농양의 증상으로는 심한 동통, 치아 뿌리의 부종 발생, 체온 상승, 두통 등이 있습니다. 찬 것이나 뜨거운 것에 예민한 반응을 보이거나, 치아를 살짝만 만져도 깜짝 놀랄 정도의 통증을 호소할 수 있습니다. 만성의 경우 통증은 없지만 잇몸에 누공이 생깁니다.</symptom>
      <diagnosis>치아 동통과 치아의 예민함이 느껴지면 근단 주위 농양을 검사해야 합니다. 근단 주위 농양은 방사선 촬영으로 진단하며, 통상적으로 뿌리 끝에서 염증이 발견됩니다.</diagnosis>
      <progress>세균의 독성 산물이 퍼져 치아 뿌리에 육아 조직이 자라기도 합니다. 이 경우 치근단 절제술(뿌리끝 절제시술)을 받아야 합니다. 뿌리 끝에 주머니와 같은 낭종이 생기기도 합니다. 낭종은 치아 뿌리 외에 주위의 뼈도 파괴하므로, 빨리 치료를 시행해야 합니다.</progress>
      <caution>근단 주위 농양은 한 번에 치료를 마무리하기 어려우므로 마무리될 때까지 치료받아야 합니다. 치료 중 딱딱한 음식을 씹다가 치아가 부러질 수도 있으므로 치료가 끝날 때까지는 치료받는 부분으로 음식을 씹지 말아야 합니다.</caution>
    </description>
  </disease>
  <disease>
    <name>치근낭(Radicular cyst)</name>
    <related_diseases>
      <related_disease>근단 주위 농양</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>치아 흔들림</related_symptom>
      <related_symptom>치근단 부위 부종</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>여러 가지 원인에 의해 치아의 뿌리 끝에 물혹이 발생한 것을 것을 말합니다.</definition>
      <cause>치아가 심한 충치 등으로 인해 치아 뿌리 끝까지 손상되어 치아 뿌리 끝에 염증이 물혹으로 변화된 것을 말합니다.</cause>
      <symptom>대부분은 증상이 없으나 낭종이 커지면 부종이 나타납니다. 낭종에 의해 뼈가 녹으면 치아가 흔들릴 수 있고 뼈 부위까지 팽창됩니다.</symptom>
      <diagnosis>방사선 사진을 촬영하여 보면 경계가 선명한 주머니가 뿌리 끝에 달려 있는 것을 볼 수 있습니다.</diagnosis>
      <progress>거의 증상이 없거나 주머니가 커지지 않고 존재하기도 하지만 대부분은 크기가 커지게 되면 주위 뼈를 녹이게 됩니다. 자극에 의해 낭종이 커지면 심하게 붓거나 뼈를 녹이며 치아가 흔들릴 수도 있습니다.</progress>
      <caution>신경치료는 하루에 끝나지 않을 수 있습니다. 치료를 받고 있는 치아 쪽으로 단단한 음식을 씹다가 치아가 부러질 염려가 있으니 주의가 필요합니다.</caution>
    </description>
  </disease>
  <disease>
    <name>만성 치주염(Chronic periodontitis)</name>
    <related_diseases>
      <related_disease>당뇨병</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>고름</related_symptom>
      <related_symptom>치아 흔들림</related_symptom>
      <related_symptom>치아가 솟은 느낌</related_symptom>
      <related_symptom>치아 벌어짐</related_symptom>
      <related_symptom>구취</related_symptom>
      <related_symptom>잇몸염증</related_symptom>
      <related_symptom>치아 통증</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>치아 주위 조직의 염증으로 잇몸(치은)과 치아를 지지해 주는 뼈(치조골)을 파괴하는 병으로 일반적으로 풍치라고 알려져 있으며, 전문 용어로는 치주 질환, 치은염(잇몸 염증), 치주염(뼈까지 파괴된 염증)이라 합니다.</definition>
      <cause>만성 치주염의 원인은 세균과 음식물 찌꺼기(치태, 프라그)가 안에서 칼슘 성분과 합쳐져 단단한 치석이 형성되어 치주낭이 생기고 치아지지골(치조골)을 파괴하게 되어 잇몸병의 증상으로 발현하게 됩니다. 

잇몸병의 진행에 영향을 미치는 요소들로는 잘못된 보철물이나 부정교합(아랫니와 윗니가 맞물리지 않음), 흡연, 스트레스, 이 악물기, 이갈이, 혀 내밀기 등의 나쁜 습관, 약물 복용, 나이, 인종, 성별, 호르몬의 변화도 영향을 미치고 당뇨병, 심혈관계 질환, 임신, 영양 이상 등 다른 전신적인 질환이나 불균형도 원인이 됩니다.
  일부 유전 질환이 원인이 되기도 합니다. 유전적인 요인이 부모에게 있으면 세균에 대한 반응이 더 빨라져서 일찍 치아를 상실하게 됩니다.
 </cause>
      <symptom>칫솔질을 할 때 잇몸에서 피가 나고 치아가 흔들리며 치아가 힘이 없어져 음식을 씹기가 힘들어집니다. 잇몸이 들뜬 느낌이 들고 입 냄새(구취)가 심해져 대인관계가 불편해집니다. 잇몸에 볼록하게 고름이 차 올라오고 잇몸이 붉게 변하며 건드리면 아프기 시작합니다. 치아의 사이가 벌어지고 위치의 변화가 생깁니다. 초기에는 대개 별로 아프지 않고 상당히 진전되어야 불편함을 느낍니다. 일반적으로 만성 치주염은 주로 30대 후반 이후에 증상이 나타나는 경우가 많습니다. 하지만 어떤 치주염은 10대부터 잇몸이 안 좋아지기도 합니다.

잇몸병의 진행 과정은 다음과 같습니다.
1. 치은염-잇몸이 붓고 붉어지며 칫솔질 시 피가 납니다.                          
2. 초기치주염- 잇몸이 붓고 들뜬 느낌이 나고 붉어지며 건드리면 피가 납니다.
3. 중기치주염- 잇몸이 내려가고 이 사이가 뜨기 시작하며 약간씩 흔들리기 시작합니다.
4. 진행된 치주염-잇몸이 심하게 내려가고 이 사이가 벌어지며 치아가 흔들립니다.</symptom>
      <diagnosis>탐침(포켓)을 이용하여 치아와 잇몸 사이에 생긴 치주낭의 깊이를 측정하고, X-선 사진을 찍어 치아 주위의 골 지지가 얼마만큼 손실되었는지를 파악합니다.</diagnosis>
      <progress>치주 치료를 받고 나면 일시적인 합병증이 있을 수 있는데 치아가 시리고 흔들리거나, 치아 사이에 공간이 형성되고 잇몸이 내려앉을 수 있습니다. 이 밖에도 출혈, 통증, 감각 이상 등이 있을 수 있으나 시간이 경과하면서 서서히 증상이 사라집니다.</progress>
      <caution>만성 치주염 환자는 치료 후에 살균 구강청정제를 정기적으로 사용해야 하고 구강 위생을 청결히 하기 위해 최소한 하루 세 번 칫솔질을 하고 치실을 사용하여 플라그와 치석이 쌓이지 않도록 해야 합니다. 흡연자는 금연하여 더 이상의 잇몸 퇴축과 치아가 느슨해지는 것을 막아야 합니다.</caution>
    </description>
  </disease>
  <disease>
    <name>턱크기의 주요 이상(Major anomalies of jaw size)</name>
    <related_diseases>
      <related_disease>안면 비대칭</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>턱의 통증</related_symptom>
      <related_symptom>턱끝이 커보임</related_symptom>
      <related_symptom>얼굴이 밋밋함</related_symptom>
      <related_symptom>발음 이상</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>아래턱이 위턱보다 큰 경우 흔히 주걱턱이라는 말을 사용하는데, 주걱턱(하악 돌출증, 하악 전돌증)이라는 것은 아래턱이 위턱에 비하여 비정상적으로 커 부정교합이 있는 경우이고, 부정교합이 없이 턱의 길이만 긴 경우는 긴턱이거나 턱끝 비대증에 속합니다.
  무턱은 아래턱뼈 자체가 뒤에 위치할 뿐만 아니라 크기가 작아서 턱이 없는 것처럼 보이는 것을 말합니다. 무턱은 두 종류로 나누어지는데 턱골격 전체가 작고 뒤로 밀려나 있으면 하악왜소증, 턱 끝 부분만 작고 후퇴되어 있으면 턱끝왜소증이라고 합니다.</definition>
      <cause>주걱턱이 생기는 원인은 위턱뼈에 비해서 아래턱뼈가 지나치게 성장한 것으로 유전적인 성향이 강한 편이지만 반드시 유전되는 것은 아니며, 어려서의 습관(아래턱을 앞으로 내미는 행동 등)이나 외상, 위턱과 아래턱을 연결하는 근육들의 비정상적 작용, 동정맥 기형이나 림프 기형과 같은 질환 등이 원인이 되는 경우도 있습니다.
  주걱턱과 마찬가지로 턱뼈의 크기나 형태는 유전적인 경향이 크기 때문에 친가나 외가쪽에 무턱인 사람이 있다면 무턱이 될 확률이 있습니다. 이 밖에 선천적인 요인으로 자궁 내 이상 및 태아손상이나 하악과두 무형성증을 들 수 있고, 외상이나 류마티성 관절염, 감염증, 부정교합, 악관절강직증, 악관절염, 방사선 치료 등에 의한 후유증, 종양 절제 등에 의한 후천성 원인으로 무턱이 되기도 합니다.</cause>
      <symptom>주걱턱은 아래턱이 위턱보다 더 앞으로 튀어나와 보이며, 동양인에게서 많이 나타납니다. 말할 때 발음이 부정확하고, 음식물을 씹을 때도 치아가 맞지 않아서 불편하고 치아는 정상이지만 턱끝이 강조되어 보이고 커 보이는 느낌이 있고, 얼굴이 밋밋하거나 긴 느낌이 있으며, 턱관절에서 소리가 나거나 통증이 있습니다.
 </symptom>
      <diagnosis>일반적으로 임상적 관찰과 심리적 환경적 문제를 분석하는 자세한 문진, 파노라마 X-ray를 통하여 대체적인 진단이 가능합니다. 최근에는 평면적인 방사선 검사가 아니라 삼차원 전산화 단층촬영(3D-CT)을 통하여 피부 표면부터 뼈에 이르기까지 입체적인 구조를 확인함으로써 정확한 진단이 가능하고, 수술을 계획하고 있는 경우 정밀한 사전 계측과 시뮬레이션을 통하여 보다 나은 결과를 가져올 수 있습니다.

입을 벌리기 어렵거나 보다 복잡한 문제가 의심되는 경우에는 MRI나 턱관절 조영술을 시행하는 경우도 있습니다. 최근에는 컴퓨터 시뮬레이션을 이용해 수술 후 자신이 변한 모습을 미리 모니터로 예상해 볼 수 있지만, 수술 결과는 뼈의 이동 뿐만 아니라 근육과 지방조직 등의 개인차에 의해서도 크게 좌우되기 때문에 이것을 전적으로 믿을 수는 없습니다.</diagnosis>
      <progress>수술 후 부기는 2-3일째 가장 심하며 4~5일이 지나면서 부기가 서서히 빠지기 시작합니다. 누워있는 것보다는 앉아있거나 가벼운 산책을 하는 것, 얼음찜질을 열심히 하는 것이 부기의 빠른 해소를 도와줍니다. 약 2-3주가 지나면 일상 생활과 사회 생활이 가능하지만 부드러운 음식을 드시고 소독액으로 가글을 할 필요가 있습니다. 잇몸과 입술의 감각이 둔해지는 경우가 종종 있지만 대개 시간이 지나며 좋아집니다. 미세한 부기가 가시고 만족스러운 얼굴 모양을 얻기까지는 3-4개월 이상이 걸리기도 합니다.  </progress>
    </description>
  </disease>
  <disease>
    <name>턱뼈 성장 이상(Anomalies of the jaw)</name>
    <related_diseases>
      <related_disease>턱관절 장애</related_disease>
      <related_disease>구순열</related_disease>
      <related_disease>구개열</related_disease>
      <related_disease>뇌성 마비</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>저작장애</related_symptom>
      <related_symptom>턱의 통증</related_symptom>
      <related_symptom>얼굴모양변화</related_symptom>
      <related_symptom>발음 이상</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>아래턱이 위턱보다 심하게 발달하거나 혹은 저성장, 턱이 아래턱보다 심하게 성장 혹은 더 많이 성장한 상태를 말합니다.
  아래턱이 위턱보다 큰 경우 흔히 주걱턱이라는 말을 사용하는데, 주걱턱(하악 돌출증, 하악 전돌증)이라는 것은 아래턱이 위턱에 비하여 비정상적으로 커 부정교합이 있는 경우이고, 부정교합이 없이 턱의 길이만 긴 경우는 긴턱이거나 턱끝 비대증에 속합니다.
  무턱은 아래턱뼈 자체가 뒤에 위치할 뿐만 아니라 크기가 작아서 턱이 없는 것처럼 보이는 것을 말합니다. 무턱은 두 종류로 나누어지는데 턱골격 전체가 작고 뒤로 밀려나 있으면 하악왜소증, 턱 끝 부분만 작고 후퇴되어 있으면 턱끝왜소증이라고 합니다.</definition>
      <cause>턱뼈의 성장 이상은 유전 등에 의해서 아래위턱의 성장이 과하거나 덜한 경우 발생합니다.
  어려서의 습관(아래턱을 앞으로 내미는 행동 등)이나 외상, 위턱과 아래턱을 연결하는 근육들의 비정상적 작용, 동정맥 기형이나 림프 기형과 같은 질환 등이 원인이 되는 경우도 있습니다.
  주걱턱과 마찬가지로 턱뼈의 크기나 형태는 유전적인 경향이 크기 때문에 친가나 외가쪽에 무턱인 사람이 있다면 무턱이 될 확률이 있습니다. 이 밖에 선천적인 요인으로 자궁 내 이상 및 태아손상이나 하악과두 무형성증을 들 수 있고, 외상이나 류마티성 관절염, 감염증, 부정교합, 악관절강직증, 악관절염, 방사선 치료 등에 의한 후유증, 종양 절제 등에 의한 후천성 원인으로 무턱이 되기도 합니다.</cause>
      <symptom>주걱턱은 아래턱이 위턱보다 더 앞으로 튀어나와 보이며, 동양인에게서 많이 나타납니다.
  말할 때 발음이 부정확하고, 음식물을 씹을 때도 치아가 맞지 않아서 불편하고 치아는 정상이지만 턱끝이 강조되어 보이고 커 보이는 느낌이 있고, 얼굴이 밋밋하거나 긴 느낌이 있으며, 턱관절에서 소리가 나거나 통증이 있습니다.
  제대로 씹을 수가 없기 때문에 밥을 먹는 시간이 길어지게 됩니다.
  무턱은 앞에서 보면 턱이 없어 보이며, 옆에서 보면 코끝과 입술, 턱 끝을 연결하는 선이 일직선으로 조화를 이루지 못하고 입이 나와 보이는데 턱 끝이 뒤로 물러나면서 피부를 끌어당겨서 입술이 뒤집혀 아랫입술이 두꺼워지고, 입을 다물면 입술 밑에 복숭아 씨처럼 주름이 생깁니다. 이 모습이 마치 심술 나서 아랫입술을 삐쭉 내밀고 있는 것처럼 보여 인상이 좋지 못하다는 소리를 듣기도 합니다.
  무턱과 구분해야 하는 상태 중 전악 전돌증(전악부 돌출증)이 있는데 이것은 앞니의 잇몸과 치아가 유난히 앞으로 튀어 나온 것으로 역시 불만스럽고 인상이 좋지 못하다는 소리를 들을 수 있습니다. </symptom>
      <diagnosis>일반적으로 임상적 관찰과 심리적 환경적 문제를 분석하는 자세한 문진, 파노라마 사진을 통하여 진단이 가능합니다.
  최근에는 평면적인 방사선 검사가 아니라 삼차원 전산화 단층촬영(3D-CT)을 통하여 피부 표면부터 뼈에 이르기까지 입체적인 구조를 확인함으로써 정확한 진단이 가능하고, 수술을 계획하고 있는 경우 정밀한 사전 계측과 시뮬레이션을 통하여 보다 나은 결과를 가져올 수 있습니다.

입을 벌리기 어렵거나 보다 복잡한 문제가 의심되는 경우에는 MRI나 턱관절 조영술을 시행하는 경우도 있습니다. </diagnosis>
      <progress>무턱증을 치료하지 않는 경우 씹기가 어려워 식사하기 힘들기 때문에 소화불량이 생길 수 있으며, 입술이 다물어지지 않기 때문에 입안이 항상 건조해져서 충치 및 치주질환이 생길 수 있습니다. 턱의 위치도 좋지 못하여 턱관절증 및 얼굴형이 점점 비대칭으로 될 수 있습니다. 또한 수면 시에 혀와 턱이 기도의 출입을 방해하여 수면무호흡증이 나타날 수 있습니다.</progress>
    </description>
  </disease>
  <disease>
    <name>치열 궁 관계 이상(Anomalies of dental arch relationship)</name>
    <related_diseases>
      <related_disease>턱크기의 주요 이상</related_disease>
      <related_disease>안면 비대칭</related_disease>
      <related_disease>치조골염</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>저작장애</related_symptom>
      <related_symptom>얼굴모양변화</related_symptom>
      <related_symptom>발음 이상</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>위턱과 아래턱의 치아를 이루고 있는 형태가 좋지 못한 상태라고 말할 수 있습니다. 윗턱이 아래턱보다 많이 나와 있는 경우, 아래턱이 비정상적으로 많이 나와 있는 경우, 맞물림은 좋으나 치아가 비뚤게 난 경우를 말합니다.</definition>
      <cause>치아가 가지런하게 나지 않거나 위턱과 아래턱의 맞물림이 좋지 않은 경우 등은  유전적인 요소도 있지만 후천적인 영향도 큽니다. 치아의 크기나 악골의 크기는 유전적으로 결정되어서 변화시킬수 없지만 식습관의 변화로 인해 치아우식 및 유치의 조기탈락으로 인해 부정교합이 늘어나고 있는 추세이며 혀를 자주 내밀거나 손가락을 빠는 행위 입으로 숨을 쉬는 등의 여러 가지 원인 등으로 치아의 위치는 변할 수 있습니다.</cause>
      <symptom>입술을 다물고 있기 힘들다거나 식사할 때 치아가 맞물리지 않아서 어렵다던지 얼굴이 점점 변하는 등의 증상이 있습니다.</symptom>
      <diagnosis>머리와 치아가 전부 나오는 방사선 사진, 치아모형 채득, 얼굴 및 구강 내 사진을 촬영 후 전체적인 관계의 문제점을 파악하여 진단을 내립니다.</diagnosis>
      <progress>성장기 청소년의 경우 치아뼈의 비정상적인 성장까지 미리 예방하여 교정치료만으로 치료를 마무리할 수 있습니다. 하지만 치아의 문제점을 넘어 뼈의 성장까지 이상이 오게 되면 성인이 되어 교정치료를 동반한 수술까지 해야 합니다. 치료를 하지 않으면 음식을 씹기 힘들 수도 있으며, 양치질이 잘되지 않아서 치주 질환 및 충치가 생기기 쉬운 환경을 이루게 됩니다. 하지만 치아의 위치 이상은 미적인 기준에 따라 달라서 주관적 판단과 정확한 진찰 상담을 통해야 합니다.</progress>
      <caution>손가락을 빨거나 혀를 내밀거나 입을 숨을 쉬는 등의 나쁜 습관은 빨리 고치는 것이 좋으며, 충치가 심하게 생긴 치아들을 빨리 치료하여 치아들이 자기 자리를 잘 지키고 있게 하는 것이 중요합니다.</caution>
    </description>
  </disease>
  <disease>
    <name>턱관절 장애(Temporomandibular joint disorders)</name>
    <related_diseases>
      <related_disease>턱크기의 주요 이상</related_disease>
      <related_disease>턱뼈 성장 이상</related_disease>
      <related_disease>턱관절 탈구</related_disease>
    </related_diseases>
    <related_symptoms>
      <related_symptom>관절잡음</related_symptom>
      <related_symptom>턱의 통증</related_symptom>
      <related_symptom>두통</related_symptom>
      <related_symptom>개 폐구 장애</related_symptom>
      <related_symptom>방사통</related_symptom>
    </related_symptoms>
    <medDeps/>
    <synonym></synonym>
    <description>
      <definition>턱관절 장애는 저작근 및 턱관절의 여러가지 질환을 포함하는 용어로 턱관절에서 잡음이 들리고, 통증이 있으며 입을 열거나 닫는데 어려움이 있는 질환입니다.
     </definition>
      <cause>단단한 음식을 오래 씹거나 이를 악무는 습관, 외상과 스트레스가 가장 큰 원인입니다. </cause>
      <symptom>입을 벌릴 때 귀, 뺨, 관자놀이 등에서 통증이 나타나거나 '딱딱' 소리가 나기도 하며, 심할 경우 입을 벌릴 수 없거나 갑자기 입을 다물 수 없는 경우도 있습니다.
 </symptom>
      <diagnosis>어금니 맞물림을 확인하는 교합 검사, 관절 상태와 뼈 조직의 이상 유무를 확인하는 방사선 사진, MRI, 근육의 긴장도를 평가하는 근전도 검사 등이 있습니다.</diagnosis>
      <progress>턱관절 장애를 장기간 방치할 경우 턱관절에 관절염이 발생할 수도 있으며,턱의 비대칭유발과 입을 거의 못 벌릴 수도 있습니다. 턱관절이 불편하면 식사를 제대로 하기 어려우며 음식을 제대로 씹지 않은 상태에서 음식을 넘기면 소화불량 등이 초래됩니다.</progress>
      <caution>입을 크게 벌리지 않도록 조심합니다. 턱을 장시간 긴장하지 않도록 합니다. 통증 있는 부위는 따뜻한 찜질을 합니다. 단단하고 질긴 음식은 피하는 것이 좋습니다. 치아 사이가 늘 떨어져 있는 습관을 유지하는 것이 좋습니다.</caution>
    </description>
  </disease>
  <disease>