<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE interventions SYSTEM "[
<!ELEMENT intervention (name, related_parts, related_areas, related_interventions, related_diseases, related_bodies, medDeps, descrips)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT related_diseases (related_disease)*>
<!ELEMENT related_disease (#PCDATA)>
<!ELEMENT related_bodies (related_bodies)*>
<!ELEMENT related_body (#PCDATA)>
<!ELEMENT related_parts (related_parts)*>
<!ELEMENT related_part (#PCDATA)>
<!ELEMENT related_areas (related_areas)*>
<!ELEMENT related_area (#PCDATA)>
<!ELEMENT related_interventions (related_interventions)*>
<!ELEMENT related_intervention (#PCDATA)>
<!ELEMENT medDeps (medDeps)*>
<!ELEMENT medDep (#PCDATA)>
<!ELEMENT description (definition, indication, preparation, stage, method, result, caution, tip)*>
<!ELEMENT definition (#PCDATA)>
<!ELEMENT indication (#PCDATA)>
<!ELEMENT symptom (#PCDATA)>
<!ELEMENT preparation (#PCDATA)>
<!ELEMENT stage (#PCDATA)>
<!ELEMENT method (#PCDATA)>
<!ELEMENT result (#PCDATA)>
<!ELEMENT caution (#PCDATA)>
<!ELEMENT tip (#PCDATA)>
]">
<!--Seongtae Kim 2020-06-06 https://github.com/Seongtae-Kim -->
<interventions>
  <intervention>
    <name>경피적 간담도조영술(Percutaneous transhepatic cholangiography)</name>
    <related_parts>
      <related_part>배</related_part>
    </related_parts>
    <related_areas>
      <related_area>소화기질환</related_area>
    </related_areas>
    <related_interventions/>
    <related_diseases>
      <related_disease>간경화(Liver cirrhosis)</related_disease>
      <related_disease>간내 담석(IHD stone)</related_disease>
      <related_disease>간이식 후 상태(Liver Transplantation status)</related_disease>
      <related_disease>선천성 담관 폐쇄증(Congenital Atresia of Bile Ducts)</related_disease>
      <related_disease>원발성 담즙성 경화증(Primary Biliary cirrhosis)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>경피적 간담도조영술은 담도에 조영제를 직접 투여한 후 X-선 촬영을 하여 담도의 구조와 형태, 비정상적인 병변을 관찰하기 위한 검사입니다. 주로 간이식 수술 시 삽입한 담도 배액관을 통해 조영함으로써 영상을 통해 관찰할 수 있다는 장점이 있습니다. 시술 과정에서 소량의 방사선에 노출됩니다.</definition>
      <preparation>시술 전 4시간 금식합니다.
  당뇨로 인슐린을 투약 중인 경우, 혈압강하제나 혈전 용해제를 투약 중인 경우, 신장질환이 있는 경우, 조영제 등의 약물 부작용 과거력이 있는 경우, 심장질환이나 폐질환, 알레르기질환을 보유한 경우 시술 전 반드시 의료진에게 해당사항에 대해 알려주어야 합니다.
  임산부의 검사를 진행할 경우 태아에게 방사선 피폭에 따른 영향이 있을 수 있으므로 검사 전 임신 여부 및 가능성에 대해 의료진에게 알리도록 합니다.
  이전의 검사 시 조영제 알레르기 반응이 있었거나 평소 음식이나 특정 물질 또는 약물에 대한 알레르기 반응이 있다면 미리 알리도록 합니다.
  시술 전 초음파, CT, MRI 등을 이용하여 간담도의 상태를 확인합니다.</preparation>
      <indication>간기능 수치 이상, 황달, 상복부 통증, 소화불량 등의 담도계 이상 증상이 있을 때 시행하게 됩니다. </indication>
      <method encoding="unicode">1. 담도에 삽입된 배액관의 위치를 영상으로 확인합니다.
2. 식염수로 배액관의 개통 여부를 확인합니다.
3. 배액관을 통하여 조영제를 주입하여 담도의 모습이나 폐쇄 유무, 합병증 유무 등을 확인한 후 시술을 종료합니다.  </method>
      <result encoding="unicode">정확한 판독이 이루어진 후 의료진을 통해 검사결과에 대한 설명을 들을 수 있습니다.</result>
      <caution encoding="unicode">도관이 막힌 경우는 조영술을 시행하지 않습니다.
  조영제에 대한 과민 반응, 조영제 사용으로 인한 신장 기능 저하 등 조영제와 관련된 부작용이 발생할 수 있습니다. 조영제 사용 전·후로 적절한 처치를 시행합니다. 
  침습적인 시술이므로 천자로 인한 감염, 출혈, 기흉, 통증 등의 부작용이 있을 수 있습니다. </caution>
    </description>
  </intervention>
  <intervention>
    <name>혈당 검사(Blood sugar test)</name>
    <related_parts>
      <related_part>전신</related_part>
    </related_parts>
    <related_areas>
      <related_area>유방내분비질환</related_area>
    </related_areas>
    <related_interventions/>
    <related_diseases>
      <related_disease>당뇨망막병증(Diabetic retinopathy)</related_disease>
      <related_disease>당뇨병(Diabetes mellitus)</related_disease>
      <related_disease>당뇨병성 말초신경병증(Diabetic polyneuropathy)</related_disease>
      <related_disease>당뇨병성 족부 질환(DM foot ulcer)</related_disease>
      <related_disease>당뇨병성 케톤산증 (Diabetic ketoacidosis)</related_disease>
      <related_disease>인슐린 비의존성 당뇨병(Non-insulin dependent diabetes mellitus)</related_disease>
      <related_disease>인슐린 의존성 당뇨병(Insulin-dependent diabetes mellitus)</related_disease>
      <related_disease>임신성 당뇨병(Gestational diabetes)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>당뇨병은 인슐린의 분비량이 부족하거나 제대로 기능을 하지 않아 발생하는 대사질환으로, 혈액 속의 포도당 수치가 정상인보다 높고 소변으로 포도당이 배출된다고 하여 이름 붙여진 병입니다. 당뇨병의 진단과 치료를 위해서는 지속적인 혈당 측정이 필요하며, 공복 시에 측정하는 공복혈당검사, 경구로 포도당 섭취 후 2시간 이후에 시행하는 경구 당 부하 검사, 당화혈색소 검사 (HbA1c), 집에서 간편하게 시행하는 자가혈당측정방법이 있습니다.
  ▶공복혈당: 100 mg/dl 미만
▶경구 당부하 검사 후 2시간 혈당: 140 ㎎/dl 미만
▶당화혈색소: 환자의 건강상태에 따라 조절목표가 달라질 수 있으나, 보통 6.5~7% 미만으로 유지할 것을 권고하고 있습니다. </definition>
      <stage>정상인이나 임신부, 내분비 질환, 자가면역질환 등 전신질환이 있는 경우 혈당 수치를 보기 위해 시행하며, 당뇨병의 진단 및 혈당 모니터를 위해 검사를 시행할 수 있습니다. </stage>
      <preparation>경우에 따라 검사 전 금식이 필요할 수 있습니다.</preparation>
      <method encoding="unicode">▶자가혈당측정방법
혈당측정을 위한 준비물: 자가혈당측정기, 채혈기, 채혈침(란셋), 시험지(스트립), 혈당 관리수첩
1. 시험지의 유효기간 및 시험지와 기계의 코드 번호가 일치 여부를 확인합니다.
2. 비누로 손을 깨끗이 닦고 완전히 건조시킵니다. 손을 알코올 젤로 소독한 경우, 손을 완전히 말린 후 혈당을 측정합니다.
3. 혈액 순환을 위해 충분히 손을 비빈 후 손바닥부터 손가락까지 부드럽게 밀어줍니다.
4. 채혈침으로 손가락 가장자리를 찌릅니다. 손가락 가운데부분보다 가장자리는 통증이 덜합니다. 혈당 검사 시마다 채혈부위를 변경합니다.
5. 손가락을 찌르고 난 후 혈액방울이 알맞은 크기가 될 때까지 손가락 끝 쪽으로 부드럽게 밀어줍니다. 이때 손가락 끝을 쥐어짜게 되면 조직액이 새어 나와 혈액이 희석되면 검사 결과에 오차가 생길 수 있으므로, 일단 채혈침으로 손가락을 찌른 후에는 손가락 끝을 세게 쥐어짜지 않도록 합니다.
6. 검사 시험지에 혈액을 묻히고 결과를 읽은 후 혈당검사 결과를 당뇨병 관리수첩에 기록합니다. 측정 당시의 운동, 식사량과 종류, 감정 상태를 함께 기록합니다.
7. 다 쓴 채혈침은 분리해서 버립니다.
▶채혈 검사
환자의 정맥에서 채혈된 혈액검체를 통해 검사합니다.
▶공복 혈당 검사(fasting blood glucose, FBG)는 식후 최소 8시간 후 공복 상태의 혈당을 측정하는 검사입니다.
▶경구 당 부하  검사는 공복 혈당 검사 후에 경구로 포도당을 섭취한 후, 2시간 이후에 시행하는 검사입니다.
▶당화혈색소 검사(HbA1c)는 지난 2~3개월 동안의 혈중 포도당의 평균치를 평가하는 검사로 최근의 운동이나 음식섭취에 영향을 받지 않기 때문에 혈당 조절을 평가하는 유용한 기준으로 사용되는 검사입니다. </method>
      <result encoding="unicode">다음 네 가지 항목 중 어느 한 가지에 해당될 경우 당뇨병이라고 진단할 수 있습니다.

1. 8시간 이상 금식한 상태에서 측정한 혈당(공복혈당)이 126 mg/dL 이상인 경우
2. 포도당 75g을 물 300cc에 녹여 5분에 걸쳐 마신 후(경구당부하검사) 2시간 째 측정한 혈당이 200 mg/dL 이상인 경우
3. 당화혈색소 검사결과가 6.5% 이상인 경우
위의 세 가지 검사는 명백한 고혈당이 아니라면 다른 날에 반복 검사를 시행합니다.
4. 다뇨, 다음, 체중감소와 같은 당뇨병의 전형적인 증상이 있으면서 식사 시간과 무관하게 측정한 혈당이 200 mg/dL 이상인 경우</result>
      <caution encoding="unicode">혈당은 음식, 스트레스, 흡연 등에 영향을 받기 때문에 명백한 고혈당의 증상이나 급성대사이상이 있는 경우를 제외하고는 두 번 이상 진단기준을 만족하면 당뇨병으로 진단하게 됩니다. </caution>
      <tip encoding="unicode">당뇨병 관리는 생활관리라고 말할 정도로 생활 전반을 조정해야 하는 병입니다. 당뇨병이 있기 전에는 염두에 두지 않았던 모든 행동들, 예를 들면 식사를 간단히 때우거나 바빠서 식사시간을 뒤로 미루었던 경우와 같은 생활패턴을 조정해야 합니다.
  당뇨인들이 시간 관리를 잘하기 위해서는 첫째, 규칙적인 식사, 운동, 약물 복용이 유지되고 있는지 둘째, 감당하기 힘든 일들이 주위에 있는지 셋째, 당뇨병 관리를 위해 필요한 시간이 충분히 있는지 넷째, 본인의 일상 생활이 스케줄화 될 수 있는지 여부를 확인해 보아야 합니다. 
  아래의 내용은 당뇨병 관리를 하는데 있어서 생활 및 시간관리와 관련된 질문들입니다. 자신의 경우와 비교해 보시기 바랍니다.
1. 나는 매일 비슷한 시간에 기상과 취침을 한다.
2. 나는 식사시간이 규칙적이고, 정해진 시간에 운동을 한다.
3. 나는 경구용 약물이나 인슐린을 매일 정해진 시간에 복용한다.
4. 나는 혈당체크를 정해진 시간에 한다.
5. 나는 내가 하는 일에 책임을 다할 수 있는 만큼 충분한 시간을 가지고 있다.
6. 내가 맡은 일이 너무 부담스럽거나 감당하기 힘들면 일의 양을 줄인다.
  당뇨병 관리는 생활관리이며 규칙적인 시간관리가 중요합니다. 앞으로 생활 및 시간 관리표를 만들어 한 단계씩 실천해 보시기 바랍니다.</tip>
    </description>
  </intervention>
  <intervention>
    <name>청력 검사(Audiometry)</name>
    <related_parts>
      <related_part>귀</related_part>
    </related_parts>
    <related_areas>
      <related_area>귀코목질환</related_area>
    </related_areas>
    <related_interventions/>
    <related_diseases>
      <related_disease>감각신경성 난청(Sensorineural hearing loss)</related_disease>
      <related_disease>난청(hearing loss)</related_disease>
      <related_disease>노인성 난청(Presbycusis)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>청력검사는 소리를 듣는 능력을 평가하는 검사로, 청력이 손실되었는지를 판별하는 검사입니다. 손실이 있을 경우, 손실의 정도와 유형을 평가 및 진단하여 치료와 재활 계획을 세우기 위해 시행합니다. 
청력검사에는 주관적인 방법과 객관적인 방법이 있습니다. 주관적 방법에는 음차검사, 순음청력검사, 어음청력검사, 자기청력검사, 누가현상검사, 청각피로검사 등이 포함되고, 객관적 방법에는 임피던스 청력검사, 전기와우도, 청성뇌간반응 청력검사, 이음향방향 검사 등이 포함됩니다. </definition>
      <preparation>성인에서는 특별한 준비 사항이 필요없으나 소아의 경우 객관적인 청력검사 시에 진정 약물을 투여하고 검사를 진행합니다. </preparation>
      <indication>평소보다 청력이 감소하였을 경우, 청력 손실의 유무와 치료의 방향을 결정할 때 검사를 시행합니다.</indication>
      <method encoding="unicode">순음청력검사(Pure tone audiometry, PTA)
하나의 주파수를 갖는 전기적 순음을 발생시켜 각 주파수에 따라 음의 강도를 조절하여 청력을 검사하는 방법입니다. 청력의 가장 기본적인 검사 방법으로, 기도청력검사와 골도청력검사를 시행하여 비교하는 방법입니다. 검사실에서 소리가 들리면 버튼을 누르고, 들리지 않으면 버튼을 누르지 않는 방법으로 검사를 진행합니다.
  어음청력검사(Speech audiometry, SA)
일상적인 의사소통능력을 알아보기 위한 검사로, 언어의 청취능력 및 이해능력을 평가합니다. 
  임피던스 청력검사(Immittance auditometry, IA)
소리가 외이를 통해 내이로 전달되는 과정에서 고막과 중이의 기능을 평가하는 검사입니다. 귀마개를 통해 한 가지 주파수의 음자극을 준 뒤 고막으로부터 반사되는 음 에너지를 측정하는 방법으로 검사를 진행합니다.
  전기와우도검사(Electrocochleography, ECoG)
전극을 외이도에 삽입하거나 고막을 통해 중이 내로 삽입하여 음 자극에 따른 달팽이관의 전기적 반응을 기록하는 검사입니다. 
  뇌간 유발 반응 청력검사(Auditory brainstem response threshold test, ABR) 
음 자극에 따라 청신경계의 반응을 기록하는 검사 방법으로, 유소아 난청의 선별검사 등에 사용되는 방법입니다. 
  유발 이음향 방사 검사(Evoked otoacoustic Emission Test, EOAE) 
외유모세포의 소리를 밖으로 방출하는 이음향 방사 기능을 검사하는 방법으로, 유소아 난청의 선별검사, 이독성의 조기 진단 등에 유용하게 사용되는 방법입니다. 
  유소아 청력검사
순음청력검사를 할 수 없는 유소아에서 조기에 청력 소실을 발견하여 치료하여 언어, 사회적 지체를 막기 위해 시행하는 검사입니다. </method>
      <result encoding="unicode">정확한 판독이 이루어진 후 의료진을 통해 검사결과에 대한 설명을 들을 수 있습니다.</result>
      <caution encoding="unicode">▶검사 전에 지나치게 크게 소리를 지르거나, 큰 소리를 듣지 않도록 합니다. 
▶검사를 시행할 때에는 소음이 없는 상태에서 검사를 진행합니다.
▶검사에 집중하지 않고 움직이거나 침을 삼키는 등의 행동을 하는 경우 검사 결과가 부정확할 수 있습니다. </caution>
    </description>
  </intervention>
  <intervention>
    <name>초음파 검사(Echography)</name>
    <related_parts>
      <related_part>전신</related_part>
    </related_parts>
    <related_areas>
      <related_area>근골격질환</related_area>
      <related_area>뇌신경정신질환</related_area>
      <related_area>소화기질환</related_area>
      <related_area>종양혈액질환</related_area>
    </related_areas>
    <related_interventions>
      <related_intervention>간(Liver)</related_intervention>
      <related_intervention>갑상선(Thyroid)</related_intervention>
      <related_intervention>고환(Testis)</related_intervention>
      <related_intervention>관절(Joint)</related_intervention>
    </related_interventions>
    <related_diseases>
      <related_disease>가진통(False labor)</related_disease>
      <related_disease>간 전이(Liver Metastasis)</related_disease>
      <related_disease>간경화(Liver cirrhosis)</related_disease>
      <related_disease>간내 담석(IHD stone)</related_disease>
      <related_disease>간농양(Liver abscess)</related_disease>
      <related_disease>간세포성 암종(Hepatocellular carcinoma)</related_disease>
      <related_disease>간의 양성 신생물(Benign neoplasm of the liver)</related_disease>
      <related_disease>간이식 후 상태(Liver Transplantation status)</related_disease>
      <related_disease>갈색세포종(Pheochromocytoma)</related_disease>
      <related_disease>갑상선 결절(Thyroid nodule)</related_disease>
      <related_disease>갑상선 미분화암(Undifferentiated thyroid cancer)</related_disease>
      <related_disease>갑상선 수질암(Medullary thyroid cancer)</related_disease>
      <related_disease>갑상선 여포암(Follicular thyroid cancer)</related_disease>
      <related_disease>갑상선 유두암(Papillary Carcinoma of Thyroid )</related_disease>
      <related_disease>갑상선암(Thyroid cancer)</related_disease>
      <related_disease>갑상선염(Thyroiditis)</related_disease>
      <related_disease>건 손상(Tendon injury)</related_disease>
      <related_disease>결절종(Ganglion)</related_disease>
      <related_disease>고셔병(Gaucher disease)</related_disease>
      <related_disease>고환 종양(Tumors of testis)</related_disease>
      <related_disease>고환의 염전(Torsion of testis)</related_disease>
      <related_disease>과오종(Hamartoma)</related_disease>
      <related_disease>구획 증후군(Compartment syndrome)</related_disease>
      <related_disease>급성 담낭염(Acute cholecystitis)</related_disease>
      <related_disease>난관수종(Hydrosalpinx)</related_disease>
      <related_disease>난소, 난관 이상(Disorders of ovary, fallopian tube)</related_disease>
      <related_disease>난소암(Ovarian cancer)</related_disease>
      <related_disease>난소의 양성 종양(Benign ovary tumor)</related_disease>
      <related_disease>낭포성 히그로마(Cystic hygroma)</related_disease>
      <related_disease>담관암(Cholangiocarcinoma)</related_disease>
      <related_disease>담석(GB stone)</related_disease>
      <related_disease>대동맥류(Aortic aneurysm)</related_disease>
      <related_disease>만성 담낭염(Chronic cholecystitis)</related_disease>
      <related_disease>맹장염(Appendicitis)</related_disease>
      <related_disease>바터 팽대부 암(AOV cancer)</related_disease>
      <related_disease>반흔 탈장(Incisonal hernia)</related_disease>
      <related_disease>방광암(Bladder cancer)</related_disease>
      <related_disease>복강 내 출혈(Intraperitoneal Bleeding)</related_disease>
      <related_disease>복막 가성점액종(Pseudomyxoma Peritonei)</related_disease>
      <related_disease>복막염(Peritonitis)</related_disease>
      <related_disease>복부 통증(Abdominal Pain)</related_disease>
      <related_disease>지방간(Fatty liver)</related_disease>
      <related_disease>화농성 간농양(Pyogenic liver abscess)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>초음파 검사는 우리 귀에는 들리지 않는 높은 주파수의 음파를 인체 내부로 보낸 후 내부에서 반사되는 음파를 영상화시킨 것을 말합니다. 초음파 검사는 검사하고자 하는 장기의 위치에 초음파 기구를 밀착시키면 실시간으로 장기의 움직임을 영상으로 얻을 수 있으며 장기의 구조와 형태, 혈류 흐름까지도 측정 가능합니다.
  우리 몸에 해로운 방사선을 사용하지 않아 무해하고, 신속하고 간편하게 비침습적으로 시행할 수 있는 검사로 간, 담낭, 췌장, 비장, 방광, 자궁, 난소, 전립선, 유방, 음경, 심장 등 다양한 인체 장기의 검사가 가능합니다. 또한 초음파 검사를 통해 영상을 보면서 필요시 조직검사, 배액술, 고주파 열치료 등의 치료적 시술도 가능합니다. </definition>
      <stage>간, 담낭, 췌장, 비장, 방광, 자궁, 난소, 전립선, 유방, 음경, 심장 등의 문제가 있을 경우 시행하게 됩니다. </stage>
      <preparation>경우에 따라 검사 전 금식이 필요할 수 있습니다.</preparation>
      <method encoding="unicode">1. 검사 부위에 따라 금식이 필요할 수 있습니다. 위, 십이지장, 췌장, 담낭 등의 상복부 초음파 검사 시에는 8시간 이상의 금식이 필요합니다.
2. 골반강 초음파 검사는 검사 전 물을 많이 먹고 소변은 참은 상태로 진행해야 합니다. 
3. 편안한 자세로 누워 검사를 진행합니다. 
4. 검사할 부위에 초음파가 잘 전달되도록 젤을 바릅니다. 
5. 초음파 기계를 검사 부위에 밀착시킵니다. 
6. 검사자의 지시에 따라 자세를 변경하거나 숨을 참을 수도 있습니다. 
▶예상 소요 시간은 5~15분 정도입니다. </method>
      <result encoding="unicode">정확한 판독이 이루어진 후 의료진을 통해 검사결과에 대한 설명을 들을 수 있습니다.</result>
      <caution encoding="unicode">위장관 검사 시 공기가 차 있을 경우 초음파가 투과하지 못하므로 초음파 검사를 시행할 수 없습니다. 
  골격계 질환일 경우, 심한 비만의 경우 초음파가 지방층을 투과하지 못하여 초음파 검사를 시행할 수 없습니다. </caution>
    </description>
  </intervention>
  <intervention>
    <name>간 초음파 검사(Liver Ultrasonography)</name>
    <related_parts>
      <related_part>배</related_part>
    </related_parts>
    <related_areas>
      <related_area>소화기질환</related_area>
    </related_areas>
    <related_interventions>
      <related_intervention>간(Liver)</related_intervention>
    </related_interventions>
    <related_diseases>
      <related_disease>간 전이(Liver Metastasis)</related_disease>
      <related_disease>간경화(Liver cirrhosis)</related_disease>
      <related_disease>간내 담석(IHD stone)</related_disease>
      <related_disease>간농양(Liver abscess)</related_disease>
      <related_disease>간디스토마(Clonorchisis sinensis)</related_disease>
      <related_disease>간성 뇌증(Hepatic encephalopathy)</related_disease>
      <related_disease>간세포성 암종(Hepatocellular carcinoma)</related_disease>
      <related_disease>간신 증후군(Hepatorenal syndrome)</related_disease>
      <related_disease>간염(Hepatitis)</related_disease>
      <related_disease>간의 양성 신생물(Benign neoplasm of the liver)</related_disease>
      <related_disease>간이식 후 상태(Liver Transplantation status)</related_disease>
      <related_disease>급성 A형 간염(Acute hepatitis A)</related_disease>
      <related_disease>급성 B형 간염(Acute hepatitis B)</related_disease>
      <related_disease>급성 C형 간염(Acute hepatitis C)</related_disease>
      <related_disease>급성 바이러스성 간염(Acute viral hepatitis)</related_disease>
      <related_disease>독성 간염(Toxic hepatitis)</related_disease>
      <related_disease>만성 B형 간염(Chronic hepatitis B)</related_disease>
      <related_disease>만성 C형 간염(Chronic hepatitis C)</related_disease>
      <related_disease>아메바성 간농양(Amebic liver abscess)</related_disease>
      <related_disease>알코올성 간질환(Alcoholic liver disease)</related_disease>
      <related_disease>전격성 간염(Fulminant Hepatic Failure)</related_disease>
      <related_disease>지방간(Fatty liver)</related_disease>
      <related_disease>화농성 간농양(Pyogenic liver abscess)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>간 초음파 검사는 인체에 무해한 초음파를 간에 투사하여 조직간의 밀도차에 의해 발생하는 반사체의 크기와 위치정보를 영상으로 재현한 검사입니다. 간 초음파 검사를 통해 간의 비정상적인 병변을 확인할 수 있으며 도플러를 이용할 경우 간으로 가는 혈류의 흐름도 파악할 수 있습니다. 컴퓨터 단층촬영(CT), 자기공명영상(MR)에 비해 간편하게 시행할 수 있고, 초음파를 통해 복수나 농양의 배액, 생검 등의 중재적 시술이 가능하여 유용하게 이용되고 있는 검사입니다. </definition>
      <stage>간의 종괴, 간의 악성 종양, 담석의 발견 및 평가가 필요할때, 초음파를 통해 복수나 농양의 배액, 조직검사, 고주파열치료 등 중재적 시술이 필요할때 시행하게 됩니다. </stage>
      <preparation>음식물 섭취 시 장 운동으로 인해 정확한 검사가 어려울 수 있으므로 검사 전 8시간 이상 금식하여야 합니다.</preparation>
      <method encoding="unicode">1. 검사는 침대에 누운자세로 진행하게 됩니다. 
2. 검사하고자 하는 부위에 젤리를 바르고 초음파 탐촉자를 피부에 밀착시킨 상태에서 문지르면서 검사를 시행합니다. 
3. 간을 정확하게 보기 위해 횡격막의 위치 조정이 필요할 수 있으므로 검사자의 지시에 따라 숨을 들이마시고 내쉬는 것을 조절해야 합니다. 
  예상 소요 시간은 5~15분 정도입니다. </method>
      <result encoding="unicode">영상의학과 전문의의 정확한 판독이 이루어진 후 의료진을 통해 검사결과에 대한 설명을 들을 수 있습니다. </result>
      <caution encoding="unicode">식사를 할 경우 위장관이 팽창하여 간을 가릴 수 있으므로 검사 전 금식이 필요합니다. 또한 담배, 껌도 위장 내의 공기를 채울 수 있으므로 삼가하는 것이 좋습니다. 
  최대한 간 전체를 검사하기 위해서는 검사자의 지시에 따라 호흡조절이 필요합니다. 이때 숨을 들이마실 때 배가 나오고, 내쉬면 배가 들어가는 복식호흡이 효과적입니다. </caution>
    </description>
  </intervention>
  <intervention>
    <name>혈관조영술(Angiography)</name>
    <related_parts>
      <related_part>전신</related_part>
    </related_parts>
    <related_areas>
      <related_area>종양혈액질환</related_area>
      <related_area>소화기질환</related_area>
    </related_areas>
    <related_interventions>
      <related_intervention>간(Liver)</related_intervention>
    </related_interventions>
    <related_diseases>
      <related_disease>간세포성 암종(Hepatocellular carcinoma)</related_disease>
      <related_disease>뇌경색(Cerebral infarction)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>혈관조영술은 혈관 내로 카테터를 삽입하여 조영제를 주입한 후 X-선 촬영을 시행하여 혈관의 구조와 비정상적인 병변을 확인할 수 있는 검사입니다. 혈관조영술은 검사 뿐만 아니라 좁아진 혈관을 스텐트를 삽입해서 넓혀 주고, 넓어진 혈관을 바로 잡아주고, 출혈이 있는 부위를 지혈할 수도 있어 치료적인 목적으로 시행할 수 있습니다. 
  혈관 천자 부위에서 카테터와 유도 철사를 사용하므로 약간의 통증을 느낄 수 있습니다. 혈관 내에서 카테터를 통해 조영제를 주입하므로 검사 부위에 화끈거리는 느낌이 들 수 있고 시술 과정에서 소량의 방사선에 노출됩니다.</definition>
      <stage>혈관의 협착, 혈관의 폐쇄, 경화, 경색 등이 있는 경우 혈관 질환의 증상이 있을 때 검사를 시행합니다.</stage>
      <preparation>시술 전 6-8시간 금식합니다.
  당뇨로 인슐린을 투약 중인 경우, 혈압강하제나 혈전 용해제를 투약 중인 경우, 신장질환이 있는 경우, 조영제 등의 약물 부작용 과거력이 있는 경우, 심장질환이나 폐질환, 알레르기 질환을 보유한 경우, 임신이나 임신 가능성이 있는 분은 시술 전 반드시 의료진에게 해당사항에 대해 알려주어야 합니다.</preparation>
      <method encoding="unicode">1. 시술을 위한 혈관 부위를 국소마취합니다.
2. 혈관을 주삿바늘로 뚫고 그 안으로 가는 유도 철사와 약 2-3mm 구경의 카테터(관)를 삽입하여 투시 영상을 보면서 시술하고자 하는 혈관에 접근시킵니다. 
3. 카테터가 필요한 혈관에 위치하면 조영제를 주입하여 시술에 필요한 정보를 확인합니다.
4. 검사 후 혈관에서 카테터를 제거합니다. 카테터가 삽입되었던 부위를 약 20분 동안 압박 지혈합니다. 
  대부분의 경우 계획한 검사가 가능하나 일부 환자에서 혈관의 기형, 굴곡, 검사 중 혈관의 손상이나 조영제 부작용 등으로 시술 시간이 길어지거나 시술 방법이 변경되거나 시술이 중단될 수 있습니다.
  예상 소요 시간은 30분으로 추정되나, 동시에 치료가 이루어지는 경우 시간이 더 소요될 수 있습니다.</method>
      <result encoding="unicode">검사 결과는 진료시 담당의사가 알려드립니다.</result>
      <caution encoding="unicode">도관을 삽입한 동맥 천자 부위에 지혈을 위한 모래주머니를 3~4시간 동안 올려놓아야 합니다. 이 기간 동안은 자세 변경도 최소한으로 제한합니다. 시술 후 하루 동안은 시술 부위의 출혈을 주의깊게 관찰하여야 하며, 출혈이 발생한 경우 즉시 의료진에게 알려야 합니다.
  시술 후 24시간 동안 누워서 안정을 취하고, 시술한 방향의 다리를 구부리지 말아야 합니다.
  도관을 삽입한 부위에 멍이나 붓기는 수일 내에 가라앉습니다. 
  예기치 않게 간 이외의 장기로 가는 동맥이 막히는 동맥색전이 발생할 수 있습니다. 이러한 동맥색전증은 경미한 증상만 나타나타 저절로 호전되지만 때에 따라서는 심각한 합병증이 동반될 수 있습니다. 
  조영제에 대한 과민 반응, 조영제 사용으로 인한 신장 기능 저하 등 조영제와 관련된 부작용이 발생할 수 있습니다. 조영제 사용 전후로 적절한 처치를 시행합니다. </caution>
    </description>
  </intervention>
  <intervention>
    <name>관절조영술(Arthrography)</name>
    <related_parts>
      <related_part>팔</related_part>
      <related_part>다리</related_part>
      <related_part>엉덩이</related_part>
    </related_parts>
    <related_areas>
      <related_area>근골격질환</related_area>
    </related_areas>
    <related_interventions>
      <related_intervention>관절(Joint)</related_intervention>
    </related_interventions>
    <related_diseases>
      <related_disease>골관절염(Osteoarthritis)</related_disease>
      <related_disease>관절염(Arthritis)</related_disease>
      <related_disease>관절와순 파열(Labral tear)</related_disease>
      <related_disease>류마티스 관절염(Rheumatoid arthritis)</related_disease>
      <related_disease>무릎관절증(Gonarthrosis)</related_disease>
      <related_disease>소아 류마티스 관절염(Juvenile rheumatoid arthritis)</related_disease>
      <related_disease>슬관절 장애(Internal derangement of knee)</related_disease>
      <related_disease>일과성 고관절 활액막염(Transient synovitis of hip)</related_disease>
      <related_disease>재발성 견관절 전방 탈구(Recurrent Anterior Glenohumeral Dislocation)</related_disease>
      <related_disease>통풍성 관절염(gouty arthritis)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>관절 조영술은 관절 내 방사선 물질을 주사한 후 X-선 촬영을 시행하여 관절의 구조 및 형태를 보는 검사입니다. 관절 조영술은 단순 X-선 검사로는 알 수 없는 관절면, 관절 내 연골의 상태, 주변 연조직의 상태를 보다 잘 확인할 수 있는 장점이 있습니다. </definition>
      <stage>관절 주위의 이유없이 지속되는 통증이 있거나 이상 증상이 있을때, 탈구의 진단을 위해, 연골이나 점액낭, 인대의 이상이 있을 경우 검사를 시행합니다. </stage>
      <preparation>성인의 경우 특별한 준비사항은 없으나, 소아의 경우 전신마취로 검사를 진행할 때 일정 시간 금식이 필요할 수 있습니다.</preparation>
      <method encoding="unicode">1. 침대에 똑바로 누운 자세를 취합니다. 
2. 관절 조영술을 시행할 부위에 국소마취를 시행합니다. 
3. 검사할 부위를 소독합니다. 
4. 검사침을 관절강으로 넣어 약간의 활액을 뽑아낸 다음 조영제를 주사합니다. 조영제 주입 시 뻐근하거나 저린 느낌이 들 수 있습니다. 
5. 검사침을 제거한 후 조영제가 잘 퍼지도록 관절운동을 시행합니다. 
6. 여러 자세로 X-선 촬영을 시행합니다. 
  예상 소요 시간은 30분 정도입니다. </method>
      <result encoding="unicode">정확한 판독이 이루어진 후 의료진을 통해 검사 결과에 대한 설명을 들을 수 있습니다. </result>
      <caution encoding="unicode">검사를 시행한 관절 부위는 12시간 정도 휴식을 취하는 것이 관절의 회복에 도움이 되며, 부종이 있을 경우 얼음찜질을 시행합니다. 
  검사 후 검사 부위의 통증, 열감, 부종 등이 지속되거나 심해질 경우 감염이나 혈관 손상, 신경 손상을 의심할 수 있으므로 즉시 병원으로 내원하도록 합니다. 
  검사 중 주입한 공기로 인해 검사 후 일시적으로 관절에서 소리가 날 수 있습니다. 
  조영제 주입 시 일부 환자에서 화끈거림, 통증, 가려움, 호흡곤란, 저혈압, 쇼크 등의 부작용이 생길 수 있습니다. 이전에 조영제 부작용이나 과민반응을 경험한 적이 있거나 평소 특이체질인 경우, 반드시 검사 전에 이를 의료진에게 알리도록 합니다.</caution>
      <tip encoding="unicode">생활 속에서 몇 가지 수칙을 지키면 건강한 관절을 지키는데 큰 도움이 될 수 있습니다. 
  관절이 힘들어하는 자세 피하기
오랜 시간 무릎을 과도하게 꺾거나 쪼그려 앉은 자세, 무릎을 꿇은 자세를 취하게 되면 무릎 관절과 인대에 무리를 줄 수 있습니다. 또한 다리를 꼬고 앉는 것은 고관절 주면의 근육과 인대를 긴장 시키며 골반 균형을 깨뜨리기도 합니다.
  무리한 운동 자제하기
축구, 농구, 마라톤, 등산 등 관절을 과도하게 많이 쓰는 운동을 하다보면 무릎 관절이나 어깨 관절의 손상을 줄 수 있습니다. 과격한 운동, 한계를 벗어나는 무리한 운동은 되도록 피하고, 통증이 있으면 휴식을 취하며, 증상이 심한 경우에는 의료진과 상담을 하는 것이 필요합니다. 관절에 이상이 있다면 걷기, 자전거 타기, 수영 등의 가벼운 운동을 하는 것이 좋습니다.
  편한 신발 신기
하이힐, 플랫슈즈, 작은 신발 등이 발 관절과 무릎, 척추와 고관절에 손상을 줄 수 있습니다. 적당한 굽과 쿠션 등이 있는 신발을 선택하고 바닥이 딱딱하지 않은 환경에서 운동을 하며 운동 전·후 간단한 스트레칭을 통해 관절을 풀어 주는 것이 좋습니다.
  체중 조절하기
체중이 증가하면 관절에 가해지는 압력이 늘어나 동일한 운동을 하더라도 관절에 더 많은 무리가 가해집니다. 적당한 운동과 식사 조절을 통해 적정 체중을 유지하는 것이 관절 건강에 도움이 됩니다.
  올바르고 균형잡힌 식사하기
관절에 좋은 약이나 민간 요법을 찾기보다 올바르고 균형잡힌 식사를 하는 것이 좋습니다. 술이나 탄산음료, 커피 등을 가급적 피하고 칼슘이 풍부한 멸치, 우유 등의 유제품과 견과류, 등푸른 생선, 계란, 버섯 등의 식품을 골고루 섭취하는 것이 도움이 됩니다. 또한 비타민 D 합성을 위해 적당량의 햇빛을 쬐는 것도 중요합니다.</tip>
    </description>
  </intervention>
  <intervention>
    <name>기관지조영술(Broncography)</name>
    <related_parts>
      <related_part>목</related_part>
    </related_parts>
    <related_areas>
      <related_area>호흡기질환</related_area>
      <related_area>종양혈액질환</related_area>
    </related_areas>
    <related_interventions>
      <related_intervention>기관지(Bronchus)</related_intervention>
    </related_interventions>
    <related_diseases>
      <related_disease>급성 기관지염(Acute bronchitis)</related_disease>
      <related_disease>기관 협착(Stenosis of trachea)</related_disease>
      <related_disease>기관지폐 형성이상(Bronchopulmonary dysplasia)</related_disease>
      <related_disease>기관지확장증(Bronchiectasis)</related_disease>
      <related_disease>만성 기관지염(Chronic bronchitis)</related_disease>
      <related_disease>이물질에 의한 기도막힘(Airway obstruction)</related_disease>
      <related_disease>폐렴(Pneumonia)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>기관지 조영술은 기관지 내에 조영제를 주입한 후 다양한 자세로 X-선 촬영을 하여 기관지의 구조와 형태를 확인하는 검사입니다. </definition>
      <stage>기관지염증, 기관지 확장증, 기관지 폐쇄나 기형 등이 의심될때, 지속적인 폐렴이나 객혈을 하는 경우 정확한 진단과 평가를 위해 검사를 시행합니다. </stage>
      <preparation>검사 전 8시간 금식이 필요합니다. 
  입 안에 세균이 많을 경우 검사 도중 기관지로 세균이 들어갈 위험이 있으므로 의료진의 지시에 따라 구강 청결을 유지해야 합니다. </preparation>
      <method encoding="unicode">1. 기관지 분비물을 억제하기 위해 분비물 억제제를 주사하며 필요 시 진정제를 주입할 수도 있습니다. 
2. 시술 중 구토반사를 억제하기 위해 카테터 삽입 전 코와 입에 국소마취제를 분무합니다. 
3. 코를 통해 튜브를 기관에 삽입하여 조영제를 주입합니다. 이때 숨을 들이마쉬거나 기침을 하여 조영제가 기관지에 골고루 분포될 수 있게 합니다. 
4. 환자의 체위를 변화시키면서 필요한 부위의 X-선 촬영을 합니다. 
  예상 소요 시간은 약 40분~1시간 정도입니다. </method>
      <result encoding="unicode">정확한 판독이 이루어진 후 의료진을 통해 검사결과에 대한 설명을 들을 수 있습니다.  </result>
      <caution encoding="unicode">검사 후 마취가 풀리고 구토반사가 돌아올 때까지 금식합니다. 구토반사가 돌아오지 않으면 음식물이나 이물질이 기도로 흡인될 수 있습니다. 
  기관지조영술은 X-선을 이용한 검사로, 임신부이거나 임신 가능성이 있는 경우 의료진과 상의 후 검사 여부를 결정하여야 합니다. 
  조영제 주입 시 일부 환자에서 화끈거림, 통증, 가려움, 호흡곤란, 저혈압, 쇼크 등의 부작용이 생길 수 있습니다. 이전에 조영제 부작용이나 과민반응을 경험한 적이 있거나 평소 특이체질인 경우, 반드시 검사 전에 이를 의료진에게 알리도록 합니다.
  호흡곤란을 호소하는 환자는 검사 진행이 어려울 수 있으므로 의료진과 상의 후 검사 여부를 결정하여야 합니다. </caution>
      <tip encoding="unicode">기관지 확장증
가래와 기침이 계속되고 호흡이 힘들다면 기관지 확장증을 의심해볼 수 있습니다. 기관지 확장증은 반복적인 염증으로 인해 기관지가 비정상적으로 늘어나 원래대로 회복하기 어려운 상태로 결핵이나 폐렴 등을 앓고 난 합병증으로 생기기도 합니다. 기관지 확장증이 지속되면 피를 토하는 객혈이 있을 수 있고 호흡곤란이 심해지면서 저산소증, 청색증 등이 나타나며 심한 경우에는 사망에 이를 수도 있습니다.
  평소 기관지를 튼튼하게 하기 위래서는 잦은 환기를 통해 실내 공기를 깨끗하게 해주고 온도와 습도를 적절하게 유지해주는 것이 좋습니다. 필수적으로 금연을 하시고 가벼운 증상이 있는 경우에는 도라지차, 생강차, 배 등의 식품을 통해서 증상 완화 효과를 볼 수 있습니다.</tip>
    </description>
  </intervention>
  <intervention>
    <name>담낭조영술(Cholecystography)</name>
    <related_parts>
      <related_part>배</related_part>
    </related_parts>
    <related_areas>
      <related_area>소화기질환</related_area>
    </related_areas>
    <related_interventions/>
    <related_diseases>
      <related_disease>급성 담낭염(Acute cholecystitis)</related_disease>
      <related_disease>담낭 선근종증(Aadenomyomatosis of Gallbladder)</related_disease>
      <related_disease>담낭 용종(GB polyp)</related_disease>
      <related_disease>담낭암(GB cancer)</related_disease>
      <related_disease>담석(GB stone)</related_disease>
      <related_disease>만성 담낭염(Chronic cholecystitis)</related_disease>
      <related_disease>석회화 담낭(Porcelain GB)</related_disease>
      <related_disease>선천성 담관 폐쇄증(Congenital Atresia of Bile Ducts)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>담낭조영술은 조영제를 경구투약하거나 주사한 후 X-선 촬영을 하여 담낭의 구조와 형태, 비정상적인 병변을 관찰하기 위한 검사입니다. 조영제를 입으로 경구투약하는 경우에는 담낭에 조영제가 쌓여 X-선 사진에서 하얗게 나타납니다. 조영제를 정맥으로 주사하는 경우에는 담낭보다 담관을 잘 관찰할 수 있습니다. </definition>
      <stage>황달, 상복부 통증, 소화불량 등의 담도계 이상 증상이 있을때 시행하게 됩니다. </stage>
      <preparation>검사 전 6시간 이상 금식이 필요합니다. </preparation>
      <method encoding="unicode">경구 담낭조영술
1. 검사 전 6시간 이상 금식이 필요합니다. 
2. 검사 전날 조영제를 복용하고 12시간이 될 때 X-선 촬영을 합니다. 이는 담낭 내의 조영제의 농축 농도가 최고인 상태로 담낭의 이완기능을 관찰할 수 있기 때문입니다. 
3. 담낭의 윤곽이 잘 관찰되면 지방식이를 투여하고 30분 후 X-선 촬영을 합니다. 이때 담낭의 수축기능을 관찰할 수 있습니다. 
4. 담낭이 잘 조영되지 않을 경우 조영제 양을 증량한 후 동일한 방법으로 시행할 수 있습니다. 

정맥 담낭조영술
1. 검사 전 6시간 이상 금식이 필요합니다. 
2. 조영제를 정맥으로 주입한 후 X-선 촬영을 합니다. </method>
      <result encoding="unicode">정확한 판독이 이루어진 후 의료진을 통해 검사결과에 대한 설명을 들을 수 있습니다.</result>
      <caution encoding="unicode">검사 시 사용하는 조영제로 인해 오심, 구토, 가려움증, 발진, 호흡곤란 등의 증상이 나타날 수 있습니다. 조영제 과민반응이 있는 환자의 경우 의료진과 상의 후 검사 여부를 결정해야 합니다. 
  X-선을 이용한 검사로 임신부이거나 임신 가능성이 있는 경우 의료진과 상의 후 검사 여부를 결정하여야 합니다. </caution>
      <tip encoding="unicode">담낭(쓸개)은 간 바로 아래쪽에 붙어 있는 주머니 모양의 장기로 우리 몸의 우상복부에 위치하며, 간에서 분비된 담즙을 농축시켜 저장하는 역할을 하는 장기입니다. 
담낭 내부의 점막층이 담낭 내강으로 돌출돼 있는 모든 종괴성 병변을 담낭 용종이라고 하며 전 인구의 약 5% 정도에서 발견되는 비교적 흔한 병변으로 대부분 위험성이 없는 양성 병변입니다.
  하지만 일부에서 담낭암으로 발전할 가능성이 있다는 점과 초기 담낭암과의 감별이 어렵다는 점 때문에 주의가 필요합니다. 최근에는 건강검진으로 시행하는 복부초음파 검사의 보편화로 무증상의 담낭용종을 발견하게 되는 경우가 더욱 많아져 관심도가 높아지고 있습니다. 
  담낭 용종의 원인은 용종의 종류에 따라 다를 수 있으며 최근에는 비만과 고지혈증 인구 증가와 관련해 콜레스테롤 용종이 증가하고 있습니다.
  일반적으로 담낭용종 자체만으로는 증상이 거의 없고 우상복부 및 명치 부위의 통증이 발생할 수 있으나 담석증과 같이 심한 통증은 아닙니다.</tip>
    </description>
  </intervention>
  <intervention>
    <name>담도조영술(Cholangiography)</name>
    <related_parts>
      <related_part>배</related_part>
    </related_parts>
    <related_areas>
      <related_area>소화기질환</related_area>
    </related_areas>
    <related_interventions>
      <related_intervention>담낭(Gallbladder)</related_intervention>
    </related_interventions>
    <related_diseases>
      <related_disease>선천성 담관 폐쇄증(Congenital Atresia of Bile Ducts)</related_disease>
    </related_diseases>
    <related_bodies/>
    <medDeps/>
    <description>
      <definition>담도 조영술은 담도에 조영제를 경구투약하거나 주사한 후 X-선 촬영을 하여 담도의 구조와 형태, 비정상적인 병변을 관찰하기 위한 검사입니다. 담도 조영술은 조영제 투여 방법과 위치에 따라 경피경간 담도 조영술, T-관 담도조영술, 경정맥 담도조영술, 경구 담도조영술로 나눌 수 있습니다. </definition>
      <stage>황달, 상복부 통증, 소화불량 등의 담도계 이상 증상이 있을 때 검사를 시행합니다.</stage>
      <preparation>검사의 종류에 따라 안내를 받아 검사 준비를 하도록 합니다.</preparation>
      <method encoding="unicode">경피경간 담도조영술
1. 검사 전 6시간 이상 금식이 필요합니다. 
2. 검사자의 지시에 따라 오른쪽 팔은 머리 위로 올리고 오른쪽 옆구리 천자부위를 소독 한 후 멸균된 상태를 유지합니다. 
3. 국소마취를 시행한 후 바늘을 간 실질 깊숙이 진입시켜 조영제를 주입합니다. 담관 내로 주사침이 들어간 것이 확인되면 주사침을 고정시키고 필요시 담즙을 채취합니다. 
4. 서서히 조영제를 주입하고, 조영제가 다 주입되면 체위를 바꾸어가며 X-선 촬영을 합니다. 
  T-관 담도조영술
1. 검사 전 6시간 이상 금식이 필요합니다. 
2. 삽입해 놓은 T-tube의 배출관으로 담즙과 공기를 충분히 유출시킨 다음 머리를 낮추고 조영제를 주입하며 X-선 촬영을 합니다. 
3. 촬영이 끝난 후 T-tube bag을 연결하여 조영제가 배출될 수 있도록 합니다. 
  경정맥 담도조영술
1. 검사 전 6시간 이상 금식이 필요합니다. 
2. 조영제를 정맥으로 주입한 후 X-선 촬영을 합니다. 
  경구 담도조영술
1. 검사 전 6시간 이상 금식이 필요합니다. 
2. 검사 전날 조영제를 복용하고 12시간이 되는 시점에 X-선 촬영을 합니다. 이때가 담낭내의 조영제의 농축 농도가 최고인 상태로 담낭의 이완기능을 관찰할 수 있기 때문입니다. 
3. 담낭의 윤곽이 잘 관찰되면 지방식이를 투여하고 30분 후 X-선 촬영을 합니다. 이때 담낭의 수축기능을 관찰할 수 있습니다. 
4. 담낭이 잘 조영되지 않을 경우 조영제 양을 증량한 후 동일한 방법으로 시행할 수 있습니다. </method>
      <result encoding="unicode">정확한 판독이 이루어진 후 의료진을 통해 검사결과에 대한 설명을 들을 수 있습니다.</result>
      <caution encoding="unicode">T-관 담도조영술 시 배액관 연결부위가 오염되지 않도록 관리해야 합니다. 
  검사 시 사용하는 조영제로 인해 화끈거림, 통증, 가려움, 호흡곤란, 저혈압, 쇼크 등의 부작용이 생길 수 있습니다. 이전에 조영제 부작용이나 과민반응을 경험한 적이 있거나 평소 특이체질인 경우, 반드시 검사 전에 이를 의료진에게 알리도록 합니다.
  X-선을 이용한 검사로 임신부이거나 임신 가능성이 있는 경우 의료진과 상의 후 검사 여부를 결정하여야 합니다.</caution>
    </description>
  </intervention>
  <intervention>
    <name>방광요도조영술(Cystourethrography)</name>
    <related_parts>
      <related_part>골반</related_part>
    </related_parts>
    <related_areas>
      <related_area>신장비뇨기질환</related_area>
    </related_areas>
    <related_interventions>